#pragma once

#include <types.h>
#include "BaseFormComponent.h"

class TESForm : public BaseFormComponent { /* Size=0x28 */
    /* 0x0000: fields for BaseFormComponent */
private:
    /* 0x0004 */ u8 cFormType;
    /* 0x0008 */ uint iFormFlags;
    /* 0x000c */ uint iFormID;
    //   /* 0x0010 */ BSStringT<char> cFormEditorID;
    /* 0x0010 */ u8 pad_cFormEditorID[8];
    /* 0x0018 */ uint iVersionControl;
    /* 0x001c */ u8 cVCVersion;
    /* 0x0020 */ u8 pad_pSourceFiles[8];
    //   /* 0x0020 */ BSSimpleList<TESFile *> pSourceFiles;

public:
    static bool bFormIDsBashed;
    //   public: static NiTPointerMap<unsigned int,TESForm *>* pAllForms;
    //   public: static NiTLargePrimitiveArray<TESForm *>* pAlteredForms;
    //   public: static BSTCaseInsensitiveStringMap<TESForm *>* pAllFormsByEditorID;
private:
    static uint iTotalFormCount;

private:
    static void *pFormBuffer;

private:
    static uint iBufferSize;

private:
    static bool bEndianSwapOnSave;

public:
    TESForm(const TESForm &);
    TESForm();
    virtual ~TESForm();
    virtual void InitializeData();
    virtual void InitializeDataComponent();
    void InitializeDataAllComponents();
    virtual void ClearData();
    virtual void ClearDataComponent();
    void ClearDataAllComponents();
    virtual bool ProcessBeforeSave();
    //   public: virtual bool Load(TESFile*);
    //   public: virtual bool LoadPartial(TESFile*);
    //   public: virtual bool Save(TESFile*);
    virtual void Save();
    //   public: virtual bool LoadEdit(TESFile*);
    //   public: virtual bool SaveEdit(TESFile*);
    //   public: virtual bool SavesBefore(FORM*);
    virtual bool SavesBefore(TESForm *);
    void SaveData();
    //   public: void LoadData(TESFile*, void*, uint16_t);
    uint32_t GetDataSizeAdded();
    //   public: virtual TESForm* CreateDuplicateForm(bool, NiTPointerMap<TESForm
    //   *,TESForm *>*); public: virtual void PostDuplicateProcess(NiTPointerMap<TESForm
    //   *,TESForm *>*);
    virtual void AddChange(int32_t);
    void ForceChange(int32_t);
    virtual void RemoveChange(int32_t);
    virtual uint16_t GetSaveSize(uint32_t);
    //   public: virtual void SaveGame(BGSSaveFormBuffer*);
    virtual void SaveGame(uint32_t);
    //   public: virtual void LoadGame(BGSLoadFormBuffer*);
    virtual void LoadGame(uint32_t, uint32_t);
    //   public: virtual void InitLoadGame(BGSLoadFormBuffer*);
    virtual void InitLoadGame(uint32_t, uint32_t);
    virtual void FinishInitLoadGame(uint32_t, uint32_t);
    //   public: virtual void Revert(BGSLoadFormBuffer*);
    virtual void Revert(uint32_t);
    virtual void LoadQueuedFormData(uint16_t);
    void SaveGameDataOLD(double *, int32_t);
    //   public: void SaveGameDataOLD(NiPoint3*, int32_t);
    void SaveGameDataOLD(float *, int32_t);
    void SaveGameDataOLD(uint32_t *, int32_t);
    void SaveGameDataOLD(int32_t *, int32_t);
    void SaveGameDataOLD(uint16_t *, int32_t);
    void SaveGameDataOLD(int16_t *, int32_t);
    void SaveGameDataOLD(void *, int32_t);
    void LoadGameDataOLD(double *, int32_t);
    //   public: void LoadGameDataOLD(NiPoint3*, int32_t);
    void LoadGameDataOLD(float *, int32_t);
    void LoadGameDataOLD(uint32_t *, int32_t);
    void LoadGameDataOLD(int32_t *, int32_t);
    void LoadGameDataOLD(uint16_t *, int32_t);
    void LoadGameDataOLD(int16_t *, int32_t);
    void LoadGameDataOLD(void *, int32_t);
    void SaveNumericID(uint32_t *, int32_t);
    void LoadNumericID(uint32_t *, int32_t);
    //   public: virtual bool FindInFileFast(TESFile*);
    //   public: virtual void CheckSaveGame(BGSSaveFormBuffer*);
    //   public: virtual void FinishLoadGame(BGSLoadFormBuffer*);
    virtual void InitItem();
    uint32_t GetFileCount();
    //   public: TESFile* GetFile(int32_t);
    //   public: TESFile* GetOwnerMaster();
    //   public: void SetFile(TESFile*);
    //   public: bool IsInFile(TESFile*);
    void ClearFiles();
    //   public: BSSimpleList<TESFile *>* GetFileList();
    char *GetFormTypeString() const;
    //   public: ENUM_FORM_ID GetFormType() const;
    //   public: void SetFormType(ENUM_FORM_ID);
    //   public: virtual ENUM_FORM_ID GetSavedFormType();
    //   public: virtual void GetFormDetailedString(BSStringT<char>&);
    void RemoveFromDataStructures();
    bool GetMaster() const;
    bool GetDelete() const;
    bool GetAltered() const;
    bool GetInitialized() const;
    virtual bool GetQuestObject() const;
    virtual bool GetHasSpokenFlag() const;
    virtual bool GetHavokDeath() const;
    virtual bool GetRandomAnim() const;
    virtual bool GetNeedtoChangeProcess() const;
    bool GetBorderRegion() const;
    virtual bool GetDangerous() const;
    virtual bool GetHasPLSpecTex() const;
    bool GetIgnoreFriendlyHits() const;
    virtual bool GetObstacle() const;
    bool GetFireOff() const;
    bool GetTemporary() const;
    bool GetIgnore() const;
    bool GetNoCollision() const;
    bool GetHasResults() const;
    bool GetNoAIAcquire() const;
    bool GetReflectedByAutoWater() const;
    bool GetRefractedByAutoWater() const;
    virtual bool GetContinuousBroadcast() const;
    bool GetLockMultiBound() const;
    bool GetGlobalConstant() const;
    bool GetLODTree() const;
    bool GetChildCanUse() const;
    virtual bool GetOnLocalMap();
    bool GetInPlaceableWater();
    void SetInPlaceableWater(bool);
    virtual void SetOnLocalMap(bool);
    bool GetMustBeVisibleDistant() const;
    void SetMustBeVisibleDistant(bool);
    //   public: virtual NiColor* GetEmittanceColor();
    bool GetEmpty() const;
    bool GetResetDestruct() const;
    bool GetDestroyed() const;
    bool GetDestructible() const;
    bool GetVATSTargetOverride() const;
    bool GetDisableFade() const;
    void SetDisableFade(bool);
    bool IsStillLoading() const;
    void SetStillLoading(bool);
    bool IsRecentPCDrop() const;
    void SetRecentPCDrop(bool);
    void SetNoCollision(bool);
    void SetMaster(bool);
    virtual void SetDelete(bool);
    bool GetDeleted() const;
    void SetInitialized(bool);
    virtual void SetAltered(bool);
    virtual void SetQuestObject(bool);
    void SetIgnore(bool);
    virtual void SetHasSpokenFlag(bool);
    virtual void SetHavokDeath(bool);
    void SetRandomAnim(bool);
    virtual void SetNeedToChangeProcess(bool);
    void SetFireOff(bool);
    void SetTemporary();
    void SetBorderRegion(bool);
    void SetHasPLSpecTex(bool);
    void SetIgnoreFriendlyHits(bool);
    void SetObstacle(bool);
    void SetNoAIAcquire(bool);
    void SetReflectedByAutoWater(bool);
    void SetRefractedByAutoWater(bool);
    void SetLockMultiBound(bool);
    void SetGlobalConstant(bool);
    void SetLODTree(bool);
    void SetChildCanUse(bool);
    bool GetDisabled() const;
    void SetDisabled(bool);
    bool GetDisabledOrDeleted() const;
    void SetEmpty(bool);
    void SetResetDestruct(bool);
    void SetDestroyed(bool);
    void SetDestructible(bool);
    void SetVATSTargetOverride(bool);
    void SetHasResults(bool);
    bool IsDefaultForm() const;
    virtual void SaveObjectBound();
    //   public: virtual void LoadObjectBound(TESFile*);
    virtual bool IsBoundObject();
    virtual bool IsObject();
    virtual bool IsMagicItem();
    virtual bool IsReference();
    virtual bool IsArmorAddon();
    virtual bool IsActorBase();
    virtual bool IsMobileObject();
    virtual bool IsActor();
    virtual uint32_t GetRefCount();
    //   public: void LoadForm(TESFile*);
    virtual void Copy(TESForm *);
    virtual bool Compare(TESForm *);
    //   public: virtual void CopyComponent(BaseFormComponent*);
    //   public: virtual bool CompareComponent(BaseFormComponent*);
    void CopyAllComponents(TESForm *);
    bool CompareAllComponents(TESForm *);
    //   public: virtual bool BelongsInGroup(FORM*, bool, bool);
    //   public: virtual void CreateGroupData(FORM*, FORM_GROUP*);
    uint32_t GetFormEditorIDLength();
    virtual const char *GetFormEditorID();
    //   public: bool SetFormEditorID(HWND__*, uint32_t);
    bool SetFormEditorID(const char *);
    void SetVCVersion(unsigned char);
    unsigned char GetVCVersion();
    unsigned char GetVCPrevVersion();
    void IncVCVersion();
    void DecVCVersion();
    void SetVersionControl(uint32_t);
    uint32_t GetVersionControl() const;
    unsigned char GetCurrentUser() const;
    unsigned char GetLastUser() const;
    uint16_t GetVersionControlDate() const;
    bool IsLastUserRegion();
    bool IsCurrentUserRegion();
    void SetCurrentUserRegion();
    uint16_t GetVersionControlMonth() const;
    uint16_t GetVersionControlDay() const;
    uint16_t GetVersionControlYear() const;
    virtual bool IsParentForm();
    virtual bool IsParentFormTree();
    virtual bool IsFormTypeChild(unsigned char);
    //   public: virtual bool Activate(TESObjectREFR*, TESObjectREFR*, bool,
    //   TESBoundObject*, int32_t);
    uint32_t GetFormFlags() const;
    void SetFormFlags(uint32_t);
    uint32_t GetFormID() const;
    uint32_t GetFormIDAsSaved();
    uint32_t GetFormIDWithoutIndex() const;
    bool FormIDMatchesWithoutIndex(uint32_t) const;
    virtual void SetFormID(uint32_t, bool);
    virtual char *GetObjectTypeName();
    void *GetFormBuffer();
    uint32_t GetFormBufferSize();
    void FreeFormBuffer();
    //   public: bool ExpandChunk(CHUNK*, uint16_t);
    void __SaveData(void *, uint32_t);
    void StartForm();
    void CloseForm();
    TESForm &operator=(const TESForm &);

    static void CompressSaveBuffer();
    //   public: static void RunPostDuplicateProcess(NiTPointerMap<TESForm *,TESForm *>*);
    static TESForm *GetFormByNumericID(uint32_t);
    static TESForm *GetFormByEditorID(const char *);
    static TESForm *GetFormByFullName(const char *, unsigned char);
    static const char *GetFormTypeString(unsigned char);
    //   public: static ENUM_FORM_ID GetFormTypeFromFormString(uint32_t);
    static bool CanBeOnLocalMap(unsigned char);
    static bool IsDefaultForm(uint32_t);
    static bool FixFormEditorID(const char *);
    static bool FixFormEditorID(char *);
    //   public: static void AddCompileIndex(uint32_t&, TESFile*);
    static void ReleaseFormDataStructures();

private:
    static void InitializeFormDataStructures();
    //   public: static void AddChunk(CHUNK_ID, _ULARGE_INTEGER);
    //   public: static void AddChunk(CHUNK_ID, uint16_t);
    //   public: static void AddChunk(CHUNK_ID, int16_t);
    //   public: static void AddChunk(CHUNK_ID, uint32_t);
    //   public: static void AddChunk(CHUNK_ID, float);
    //   public: static void AddChunk(CHUNK_ID, int32_t);
    //   public: static void AddChunk(CHUNK_ID, unsigned char);
    //   public: static void AddChunk(CHUNK_ID, char);
    //   public: static void AddChunk(CHUNK_ID);
    //   public: static void AddChunkArray(CHUNK_ID, const char*, uint32_t);
    //   public: static void AddChunkArray(CHUNK_ID, const uint16_t*, uint32_t);
    //   public: static void AddChunkArray(CHUNK_ID, const int16_t*, uint32_t);
    //   public: static void AddChunkArray(CHUNK_ID, const uint32_t*, uint32_t);
    //   public: static void AddChunkArray(CHUNK_ID, const int32_t*, uint32_t);
    //   public: static void AddChunkArray(CHUNK_ID, const float*, uint32_t);
    //   public: static void __AddChunkData(CHUNK_ID, const void*, uint32_t);
public:
    static bool QEndianSwapOnSave();
    static void SetEndianSwapOnSave(bool);
    //   private: static void AddChunkArray32(CHUNK_ID, const void*, uint32_t);
    //   private: static void AddChunkArray16(CHUNK_ID, const void*, uint32_t);
};
