#pragma once

#include "bsaudio/BSSoundHandle.h"
#include "fallout/misc/saveload/BGSLoadFormBuffer.h"
#include "fallout_shared/ExtraDataObjects.h"
#include "fallout_shared/TESForm.h"
#include "fallout_shared/tesobjectrefr.h"

class Script;

class ExtraDataList : public BaseExtraList {
  public:
	ExtraDataList(const ExtraDataList&);
	ExtraDataList();
	virtual ~ExtraDataList();
	bool IsCopyableExtra(BSExtraData*);
	void RemoveAllCopyableExtra(bool);
	void RemoveNonPersistentCellData();
	void AddExtraCopy(BSExtraData*);
	void CopyList(ExtraDataList*);
	void CopyListForContainer(ExtraDataList*, bool);
	void CopyListForReference(ExtraDataList*, bool);
	void DuplicateExtraListForContainer(ExtraDataList*);
	bool CompareList(ExtraDataList*);
	bool CompareListForContainer(ExtraDataList*, bool, bool);
	void Save();
	void Load(TESFile*, TESForm*);
	void InitItem(TESForm*);
	bool IsExtraDefaultforContainer(bool);
	bool HasOnlyOwnershipNonDefault();
	void SetWeaponModSlot(unsigned char);
	bool GetWeaponModSlotActive(unsigned char);
	bool HasWeaponMods();
	void RemoveWeaponMods();
	void SetWeaponModFlags(unsigned char);
	unsigned char GetWeaponModFlags();
	void SetIsModding(bool);
	void RemoveIsModding();
	ExtraAnim* SetAnimPtr(Animation*);
	ExtraAnimSave* SetAnimSave(TESObjectREFR*);
	ExtraStartingPosition* SetStartingPositionPtr(TESObjectREFR*);
	ExtraBiped* SetBipedPtr(BipedAnim*);
	ExtraLight* SetLightPtr(REFR_LIGHT*);
	ExtraLock* SetLockPtr(REFR_LOCK*);
	ExtraTeleport* SetTeleportPtr(DoorTeleportData*);
	ExtraMapMarker* SetMapMarkerPtr(MapMarkerData*);
	ExtraAudioMarker* SetAudioMarkerPtr(AudioMarkerData*);
	ExtraAudioBuoyMarker* SetAudioBuoyMarkerPtr(AudioBuoyMarkerData*);
	ExtraAction* SetActionPtr();
	void SetRadioData(RADIO_DATA*);
	void SetOwnership(TESForm*);
	void SetGlobal(TESGlobal*);
	void SetRank(int);
	void SetWorn(bool, bool);
	void SetGhost(bool);
	void SetCanNotWear(bool);
	void SetHealth(float);
	void SetUses(unsigned char);
	void SetCount(short);
	void SetTimeLeft(float);
	void SetCharge(float);
	void SetScript(Script*);
	void SetScriptLocals(ScriptLocals*);
	void SetScale(float);
	void SetSound(const BSSoundHandle&);
	void SetCreatureAwakeSound(const BSSoundHandle&);
	void SetCreatureMovementSound(const BSSoundHandle&);
	void SetWeaponIdleSound(const BSSoundHandle&);
	void SetWeaponAttackSound(const BSSoundHandle&);
	void SetActivateLoopSound(const BSSoundHandle&);
	void SetSeedIndex(unsigned char);
	void SetContainerChanges(InventoryChanges*);
	void SetPackageStartLocation(TESWorldSpace*, TESObjectCELL*,
								 const NiPoint3&, float);
	void SetReferencePointer(TESObjectREFR*);
	void SetPackageExtra(TESPackage*, int, TESObjectREFR*, bool, bool, bool);
	void SetPackageExtraTarget(TESObjectREFR*);
	void SetPackageExtraIndex(int);
	void SetTrespassPackageExtra(TrespassPackage*);
	void AddToPlayerCrimeList(Crime*, float);
	void SetLevelItemExtra(int);
	void SetLevelItemExtraFlag(bool);
	void SetPersistentCell(TESObjectCELL*);
	void SetRagDollData(TESObjectREFR*);
	void SetRagDollDataFromCopy(RagDollData*);
	void SetRunOnceExtraPackage(TESPackage*, char);
	bool GetPackageExtraDoneOnce();
	void SetPackageExtraActionComplete(bool);
	void SetDistantDataNormal(const NiPoint3&);
	void UpdateDistantData(TESObjectLAND*, const NiPoint3&);
	void SetLastFinishedSequence(const char*);
	void AddFollower(Actor*);
	bool HasFollower(Actor*);
	ExtraFollower* GetFollowerExtra();
	void RemoveFollowerExtra();
	void RemoveFollower(Actor*);
	u8 GetTerminalState();
	void SetTerminalState(unsigned char);
	char GetTerminalLockState();
	void SetTerminalLockState(char);
	void SetHotKey(char);
	char GetHotKey();
	void RemoveHotKey();
	void SetInfoGeneralTopic(MenuTopic*);
	MenuTopic* GetInfoGeneralTopic(TESObjectREFR*);
	void RemoveInfoGeneral();
	int AddFriendHit();
	int GetFriendHitCount();
	void RemoveFriendHitsExtra();
	void SetHeadTrackTargetExtra(TESObjectREFR*);
	TESObjectREFR* GetHeadTrackTargetExtra();
	void SetRefractionPropertyExtra(bool, float);
	ExtraRefractionProperty* GetRefractionPropertyExtra();
	void SetOriginalReferenceExtra(TESObjectREFR*);
	void RemoveOriginalReferenceExtra();
	TESObjectREFR* GetOriginalReference();
	Animation* GetAnimation();
	ExtraAnimSave* GetAnimSave();
	FILE_POS_ROT* GetStartingPosition();
	BipedAnim* GetBiped();
	REFR_LIGHT* GetLight();
	REFR_LOCK* GetLock();
	RADIO_DATA* GetRadioData();
	DoorTeleportData* GetTeleport();
	MapMarkerData* GetMapMarkerData();
	AudioMarkerData* GetAudioMarkerData();
	AudioBuoyMarkerData* GetAudioBuoyMarkerData();
	TESNPC* GetOwnerNPC();
	TESFaction* GetOwnerFaction();
	TESForm* GetOwner();
	TESGlobal* GetGlobal();
	TESObject* GetObjPtr();
	int GetRank();
	bool GetWorn(bool);
	bool GetGhost();
	bool GetCanNotWear();
	ExtraLeveledItem* GetLeveledItem();
	bool HasLeveledItem();
	float GetHealth();
	u8 GetUses();
	short GetCount();
	float GetTimeLeft();
	float GetCharge();
	Script* GetScript();
	ScriptLocals* GetScriptLocals();
	float GetScale();
	void GetSound(BSSoundHandle&);
	void GetCreatureAwakeSound(BSSoundHandle&);
	void GetCreatureMovementSound(BSSoundHandle&);
	void GetWeaponIdleSound(BSSoundHandle&);
	void GetWeaponAttackSound(BSSoundHandle&);
	void GetActivateLoopSound(BSSoundHandle&);
	unsigned char GetSeedIndex();
	InventoryChanges* GetContainerChanges();
	WORLD_LOCATION* GetPackageStartLocation();
	TESObjectREFR* GetReferencePointer();
	TESPackage* GetPackageExtra();
	bool GetPackageExtraComplete();
	bool GetPackageExtraActivate();
	TrespassPackage* GetTrespassPackage();
	int GetPackageExtraIndex();
	TESObjectREFR* GetPackageExtraTarget();
	BSSimpleList<Crime*>* GetPlayerCrimeList();
	bool GetExtraLevelItemFlag();
	int GetExtraLevelItemIndex();
	TESObjectCELL* GetPersistentCell();
	RagDollData* GetRagDollData();
	char* GetLastFinishedSequence();
	char GetExtraRunOnceDay(TESPackage*);
	void RemoveRunOnceDayPackage(TESPackage*);
	void CheckRemoveRunOnceDayPackage(char);
	bool IsInRunOnceDayPackageList(TESPackage*);
	NiPoint3 GetDistantDataNormal();
	TESObjectREFR* GetEnableStateParent();
	void SetEnableStateParent(TESObjectREFR*);
	bool IsEnableStateInverse();
	void SetEnableStateInverse(bool);
	bool ShouldPopInWhenEnabledByParent();
	void SetPopInWhenEnabledByParent(bool);
	bool ShouldPopOutWhenDisabledByParent();
	void SetPopOutWhenDisabledByParent(bool);
	void SetEnableStateParentFlags(unsigned char);
	BSSimpleList<TESObjectREFR*>* GetEnableStateChildren();
	void AddEnableStateChild(TESObjectREFR*);
	void RemoveEnableStateChild(TESObjectREFR*);
	TESObjectREFR* GetItemDropper();
	void SetItemDropper(TESObjectREFR*);
	BSSimpleList<TESObjectREFR*>* GetDroppedItemList();
	void RemoveDroppedItemList();
	void AddDroppedItem(TESObjectREFR*);
	void RemoveDroppedItem(TESObjectREFR*);
	TESObjectREFR* GetDroppedWeapon();
	TESWaterForm* GetWaterType();
	void SetWaterType(TESWaterForm*);
	TESObjectREFR* GetRandomTeleportMarker();
	void SetRandomTeleportMarker(TESObjectREFR*);
	TESObjectREFR* GetAshPileRef();
	void SetAshPileRef(TESObjectREFR*);
	TESObjectREFR* GetLinkedRef();
	void SetLinkedRef(TESObjectREFR*);
	BSSimpleList<TESObjectREFR*>* GetLinkedRefChildren();
	void AddLinkedRefChild(TESObjectREFR*);
	void RemoveLinkedRefChild(TESObjectREFR*);
	BSSimpleList<REF_ACTIVATE_DATA*>* GetActivateParentList();
	REF_ACTIVATE_DATA* GetActivateData(TESObjectREFR*);
	void AddActivateParent(TESObjectREFR*);
	void RemoveActivateParent(TESObjectREFR*);
	float GetActivateDelay(TESObjectREFR*);
	void SetActivateDelay(TESObjectREFR*, float);
	bool IsActivateParentOnly();
	void SetActivateParentOnly(bool);
	BSStringT<char> GetActivateTextOverride();
	void SetActivateTextOverride(char*);
	BSSimpleList<REF_ACTIVATE_DATA*>* GetActivateRefChildren();
	void AddActivateRefChild(TESObjectREFR*);
	void RemoveActivateRefChild(TESObjectREFR*);
	void SetActivateChildrenTimer(float);
	float GetActivateChildrenTimer();
	BSSimpleList<REF_DECAL_DATA*>* GetDecalRefs();
	void AddDecalRef(TESObjectREFR*, const NiPoint3&, const NiPoint3&);
	void RemoveDecalRef(TESObjectREFR*);
	TESObjectREFR* GetOpenCloseActivateRef();
	void SetOpenCloseActivateRef(TESObjectREFR*);
	ExtraSayToTopicInfo* GetSayToExtra();
	TESObjectREFR* GetMerchantContainer();
	void SetMerchantContainer(TESObjectREFR*);
	void GetLevCreaMultiplier(float&, int&);
	int GetLevCreaModifier();
	void SetLevCreaModifier(int);
	void SetNoRumors(bool);
	void ClearRumorsExtra();
	bool HasLevCreaCalced();
	TESActorBase* GetLevCreaOriginalBase();
	TESActorBase* GetLevCreaTemplate();
	void SetLeveledCreature(TESActorBase*, TESActorBase*);
	unsigned int GetDetachTime();
	void SetDetachTime(unsigned int);
	AlchemyItem* GetPoison();
	void SetPoison(AlchemyItem*);
	REFR_LIGHT* GetSpellEffectLight();
	ExtraLight* SetSpellEffectLightPtr(REFR_LIGHT*);
	TESObjectREFR* GetXTarget();
	void SetXTarget(TESObjectREFR*);
	BGSEncounterZone* GetEncounterZone();
	void SetEncounterZone(BGSEncounterZone*);
	TESForm* GetEmittanceSource();
	void SetEmittanceSource(TESForm*);
	TESObjectREFR* GetMultiBoundRef();
	void SetMultiBoundRef(TESObjectREFR*);
	MultiBoundMarkerData* GetMultiBoundData();
	void SetMultiBoundData(MultiBoundMarkerData*);
	BSMultiBound* GetMultiBound();
	void SetMultiBound(BSMultiBound*);
	BSOcclusionPlane* GetOcclusionPlane();
	void SetOcclusionPlane(BSOcclusionPlane*);
	BSPortal* GetPortal();
	void SetPortal(BSPortal*);
	BSMultiBoundRoom* GetRoom();
	void SetRoom(BSMultiBoundRoom*);
	TESObjectREFR* GetLinkedPlaneRef(int);
	void SetLinkedPlaneRef(TESObjectREFR*, int);
	OcclusionPlaneLinkedRefData* GetOcclusionPlaneLinkedRefData();
	void SetOcclusionPlaneLinkedRefData(OcclusionPlaneLinkedRefData*);
	TESObjectREFR* GetPortalLinkedRoomRef(int);
	void SetPortalLinkedRoomRef(int, TESObjectREFR*);
	BSSimpleList<TESObjectREFR*>* GetRoomLinkedRoomRefList();
	void AddRoomLinkedRoomRef(TESObjectREFR*);
	BSSimpleList<TESObjectREFR*>* GetRoomLinkedPortalRefList();
	void AddRoomLinkedPortalRef(TESObjectREFR*);
	void RemoveRoomLinkedPortalRef(TESObjectREFR*);
	void RemoveRoomLinkedRoomRef(TESObjectREFR*);
	bool GetRoomIsLinked(TESObjectREFR*);
	bool GetRoomIsMaster();
	void SetRoomIsMaster(bool);
	TESObjectREFR* GetMasterRoom();
	TESObjectREFR* GetMasterRoomRecurse(NiTMap<TESObjectREFR*, bool>*);
	PortalLinkedRefData* GetPortalLinkedRefData();
	void SetPortalLinkedRefData(PortalLinkedRefData*);
	RoomLinkedRefData* GetRoomLinkedRefData();
	void SetRoomLinkedRefData(RoomLinkedRefData*);
	CollisionData* GetCollisionData();
	void SetCollisionData(CollisionData*);
	void SetRadius(float);
	float GetRadius();
	void SetRadiation(float);
	float GetRadiation();
	BSSimpleList<REF_REFLECTED_DATA*>* GetReflectedRefs();
	BSSimpleList<REF_REFLECTOR_DATA*>* GetReflectorRefs();
	void SetReflectedByRef(TESObjectREFR*, bool);
	void SetRefractedByRef(TESObjectREFR*, bool);
	void SetReflectsRef(TESObjectREFR*, bool);
	void SetRefractsRef(TESObjectREFR*, bool);
	void RemoveAllReflectedByRefs();
	void RemoveAllRefractedByRefs();
	BSSimpleList<TESObjectREFR*>* GetWaterLightRefs();
	BSSimpleList<TESObjectREFR*>* GetLitWaterRefs();
	void SetWaterLightRef(TESObjectREFR*, bool);
	void SetLitWaterRef(TESObjectREFR*, bool);
	void RemoveAllLitWaterRefs();
	void AddPrimitive(BGSPrimitive*);
	void RemovePrimitive();
	BGSPrimitive* GetPrimitive();
	void SetPatrolRefData(PatrolRefData*);
	PatrolRefData* GetPatrolRefData();
	void RemovePatrolRefData();
	void SetActorPackageData(ActorPackageData*);
	ActorPackageData* GetActorPackageData();
	void RemoveActorPackageData();
	void SetExtraSayTopicInfoOnceADayExtra(SayOnceTopicInfos*);
	ExtraSayTopicInfoOnceADay* GetExtraSayTopicInfoOnceADayExtra();
	void RemoveExtraSayTopicInfoOnceADayExtra();
	void SetExtraSayToInfoExtra(TESTopicInfo*);
	void RemoveExtraSayToInfoExtra();
	void SetExtraSayToTopicOnExtra(TESTopic*);
	TESTopic* GetExtraSayToTopic();
	TESTopicInfo* GetExtraSayToTopicInfo();
	void SetExtraSayToResponseIDOnExtra(unsigned int);
	unsigned int GetExtraSayToResponseID();
	TESObjectREFR* SetInWaterZone(WaterZone*, bool);
	bool GetInWaterZone(WaterZone*);
	NiTMap<WaterZone*, int>* QWaterZoneMap();
	TESObjectREFR* GetCurrentPlaceableWater();
	WaterZone* GetFirstWaterZone();
	void SetPatrolRefInUse(TESObjectREFR*);
	bool GetPatrolRefCanBeUsedBy(const TESObjectREFR*);
	ExtraFollowerSwimBreadcrumbs* GetOrCreateExtraFollowerSwimBreadcrumbs();
	ExtraFollowerSwimBreadcrumbs* GetExtraFollowerSwimBreadcrumbs();
	void RemoveFollowerSwimBreadcrumbs();
	float GetNorthRotation();
	void SetNorthRotation(float);
	SeenData* GetSeenData();
	void SetSeenData(SeenData*);
	void RemoveStartingPositionPtr();
	void RemoveAnimSave();
	void RemoveAnimPtr();
	void RemoveBipedPtr();
	void RemoveLightPtr();
	void RemoveSpellEffectLightPtr();
	void RemoveLockPtr();
	void RemoveTeleportPtr();
	void RemoveObjPtr();
	void RemoveActionPtr();
	void RemoveOwnership();
	void RemoveGlobal();
	void RemoveRank();
	void RemoveWorn(bool);
	void RemoveGhost();
	void RemoveHealth();
	void RemoveUses();
	void RemoveCount();
	void RemoveTimeLeft();
	void RemoveCharge();
	void RemovePoison();
	void RemoveScript();
	void RemoveScriptLocals();
	void RemoveScale();
	void RemoveCellCoord();
	void RemoveCellLighting();
	void RemoveCell3D();
	void RemovePathGrid();
	void RemoveSeedIndex();
	void RemoveContainerChanges();
	void RemovePackageStartLocation();
	void RemoveReferencePointer();
	void RemovePackageExtra();
	void RemoveTrespassPackage();
	void RemovePlayerCrimeListExtra(Actor*);
	void RemoveLevelItemExtra();
	void RemoveExtraRunOncePackageList();
	void RemoveCannotWearExtra();
	void RemoveLastFinishedSequence();
	void RemoveSayToInfoExtra();
	void ClearTrespassPackage(TESPackage*);
	void ClearScriptLocals();
	void SetCell3D(NiNode*);
	NiNode* GetCell3D();
	void RemoveHavok();
	void SetbhkWorld(bhkWorld*);
	bhkWorld* GetbhkWorld();
	void SetCellMopp(CellMopp*);
	CellMopp* GetCellMopp();
	void RemovePointer(EXTRA_DATA_TYPE);
	void SetPointer(void*, EXTRA_DATA_TYPE);
	void* GetPointer(EXTRA_DATA_TYPE);
	void SetRegionList(TESRegionList*);
	TESRegionList* GetRegionList();
	void SetMusicType(BGSMusicType*);
	BGSMusicType* GetMusicType();
	void SetEnvironmentType(CELL_ENVIRO_TYPE);
	CELL_ENVIRO_TYPE GetEnvironmentType();
	void SetAcousticSpace(BGSAcousticSpace*);
	BGSAcousticSpace* GetAcousticSpace();
	void SetClimate(TESClimate*);
	TESClimate* GetClimate();
	void SetImageSpace(TESImageSpace*);
	TESImageSpace* GetImageSpace();
	void SetImpactSwap(ImpactSwap*);
	ImpactSwap* GetImpactSwap();
	void SetCanopyShadowMask(int, NiRenderedTexture*, _D3DLOCKED_RECT*&);
	int GetCanopyShadowMask(NiRenderedTexture*&, _D3DLOCKED_RECT*&);
	void SetModelSwap(TESModel*, TESForm*);
	TESModel* GetModelSwap();
	void RemoveModelSwap();
	ExtraNavMeshPortal* GetNavMeshPortal();
	void SetNavMeshPortal(ExtraNavMeshPortal*);
	void RemoveNavMeshPortal();
	void SetSavedAnimation(char*);
	char* GetSavedAnimation();
	bool RestoreSavedAnimation(TESObjectREFR*);
	void RemoveSavedAnimation();
	void SetSavedHavokData(char*);
	char* GetSavedHavokData();
	bool RestoreSavedHavokData(TESObjectREFR*);
	void RemoveSavedHavokData();
	void SetTalkingActorExtra(BGSTalkingActivator*, TESObjectREFR*);
	ExtraTalkingActor* GetTalkingActorExtra();
	void RemoveTalkingActorExtra();
	void RemoveEditorID();
	void SetEditorID(const char*);
	const char* GetEditorID();
	NiPoint3 GetStartingAngle(TESObjectREFR*);
	NiPoint3 GetStartingLocation(TESObjectREFR*);
	NiPoint3* GetStartingAnglePtr(TESObjectREFR*);
	NiPoint3* GetStartingLocationPtr(TESObjectREFR*);
	NiPoint3 SetStartingAngle(TESObjectREFR*, NiPoint3);
	NiPoint3 SetStartingLocation(TESObjectREFR*, NiPoint3);
	void SetStartingWorldOrCell(TESForm*);
	void SetStartingWorldOrCellForRef(TESObjectREFR*);
	TESForm* GetStartingWorldOrCell();
	void RemoveStartingWorldOrCell();
	unsigned int GetActionFlag();
	bool GetAction(OBJECT_ACTION);
	void RunActions();
	void SetActionFlag(OBJECT_ACTION);
	void SetAction(OBJECT_ACTION);
	void ClearAction(OBJECT_ACTION);
	void SetActionRef(TESObjectREFR*);
	TESObjectREFR* GetActionRef();
	float GetHealthPerc();
	void SetHealthPerc(float);
	float GetObjectHealth();
	void SetObjectHealth(float);
	void RemoveObjectHealth();
	void AddFactionChangesExtra();
	ExtraFactionChanges* GetFactionChangesExtra();
	void RemoveFactionChangesExtra();
	ExtraDismemberedLimbs* AddDismembermentExtra();
	ExtraDismemberedLimbs* GetDismembermentExtra();
	void RemoveDismembermentExtra();
	ExtraActorCause* GetActorCauseExtra();
	void SetActorCauseExtra(ActorCause*);
	TESCombatStyle* GetCombatStyle();
	void SetCombatStyle(TESCombatStyle*);
	ExtraAmmo* GetAmmoExtra();
	void SetAmmoExtra(TESAmmo*, int);
	void AddGuard(Actor*);
	void RemoveGuard(Actor*);
	void NotifyGuardsAboutActivation(TESObjectREFR*, TESObjectREFR*);
	void SetIgnoredBySandbox(bool);
	bool GetIgnoredBySandbox();
	u16 GetSaveSize(unsigned int, TESObjectREFR*);
	void SaveGame(BGSSaveFormBuffer*);
	void SaveGame(unsigned int, TESObjectREFR*);
	void LoadGame(BGSLoadFormBuffer*);
	void LoadGame(unsigned int, unsigned int, TESObjectREFR*);
	void InitLoadGame(BGSLoadFormBuffer*, TESForm*);
	void InitLoadGame(unsigned int, unsigned int, TESObjectREFR*, TESForm*);
	void FinishInitLoadGame(unsigned int, unsigned int, TESObjectREFR*);
	void Revert(BGSLoadFormBuffer*);
	void Revert(unsigned int, TESObjectREFR*);
	void RemoveAllSaveableData(unsigned int, TESObjectREFR*);
	void FinishLoadGame(BGSLoadFormBuffer*);
	void RevertUnsavedExtra(BGSLoadFormBuffer*);
	void VerifyExtraData();

	static void ExportAllActivationTextOverrides();
	static void ImportAllActivationTextOverrides();
};
