#pragma once

#include "fallout_shared/tesform.h"
#include "fallout_shared/tesobject.h"
#include "fallout_shared/tesscriptshared.h"
#include "fallout_shared/tesscriptvariable.h"
#include "fallout_shared/tesscriptcompiler.h"

class Script : public TESForm {
public:
    Script(const Script &);
    Script();
    virtual ~Script();
    virtual void InitializeData();
    virtual void ClearData();
    void Init(ScriptCompileData *);
    bool NeedsUpdate(ScriptCompileData *);
    void CopyResultScript(Script *);
    bool CompareResultScripts(Script *);
    void SetCompileData(unsigned int, char *);
    void SaveResultScript();
    virtual void Save();
    virtual bool SaveEdit(TESFile *);
    virtual bool Load(TESFile *);
    SCRIPT_HEADER *GetHeader();
    char *GetText();
    unsigned int GetTextLength() const;
    void SetText(const char *);
    char *GetCompiledData();
    ScriptLocals *CloneLocals();
    BSSimpleList<SCRIPT_LOCAL *> *CreateLocalList();
    bool Run(TESObjectREFR *, ScriptLocals *, TESObjectREFR *, bool);
    void RunScriptEffectStart(TESObjectREFR *, ScriptLocals *);
    void RunScriptEffectFinish(TESObjectREFR *, ScriptLocals *);
    void RunScriptEffectUpdate(TESObjectREFR *, ScriptLocals *, float);
    void CompileAndRun(ScriptCompiler *, COMPILER_NAME, TESObjectREFR *);
    const char *GetVariableName(unsigned int);
    unsigned int ConvertIndexToID(unsigned int);
    char FindVariable(const char *, unsigned int *);
    void InitItem(TESForm *);
    virtual void InitItem();
    bool GetIsCompiled();
    void SetIsCompiled(bool);
    //    void SetOwnerQuest(TESQuest*);
    //    TESQuest* GetOwnerQuest();
    BSSimpleList<ScriptVariable *> *GetVariableList();
    SCRIPT_REFERENCED_OBJECT *GetReferencedObject(unsigned int, ScriptLocals *);
    BSSimpleList<SCRIPT_REFERENCED_OBJECT *> *GetReferencedObjectList();
    void ClearProfilerTimer();
    void AddProfilerTime(float);
    float GetProfilerTimer();
    float GetQuestScriptGetSecondsBuffer();

protected:
    void ClearLocalVariableRefObjects();
    void ClearAllReferenceObjects();
    void ClearVariableList();
    void EndianData();

private:
    SCRIPT_HEADER m_header; // 0x28
    char *m_text; // 0x3c
    char *m_data; // 0x40
    float fProfilerTimer; // 0x44
    float fQuestScriptDelay; // 0x48
    float fQuestScriptGetSecondsBuffer; // 0x4c
    //   TESQuest* pOwnerQuest; // 0x50
    BSSimpleList<SCRIPT_REFERENCED_OBJECT *> listRefObjects; // 0x54
    BSSimpleList<ScriptVariable *> listVariables; // 0x5c
    static TESForm *pCrimeVictim;
    //   static BSCriticalSection ScriptRefListCrit;
    static BSSimpleList<TESObjectREFR *> ReferencesToEnable;
    static BSSimpleList<TESObjectREFR *> ReferencesToDisable;
    static BSSimpleList<TESObjectREFR *> ReferencesToDelete;
    static BSSimpleList<TESObjectREFR *> ReferencesToFadeDisable;
    static bool m_bSystemOutput;
    static char m_cButtonValue;
    static unsigned int m_iButtonOwner;
    static Script *pLastRefSearchScript;
    static ScriptLocals *pLastScriptLocals;
    static unsigned int iLastRefSearchIndex;
    static SCRIPT_REFERENCED_OBJECT *pLastRefObject;

#pragma region Every Script Builtin
#define TSCRIPTFUNC_GENERIC(name)                                                        \
    static bool name(                                                                    \
        const SCRIPT_PARAMETER *,                                                        \
        const char *,                                                                    \
        TESObjectREFR *,                                                                 \
        TESObjectREFR *,                                                                 \
        Script *,                                                                        \
        ScriptLocals *,                                                                  \
        double &,                                                                        \
        unsigned int &                                                                   \
    );
#define TSCRIPTFUNC_GET_PVPVRD(name)                                                     \
    static bool name(TESObjectREFR *, void *, void *, double &);

public:
    static bool VerboseOutput();
    static void SavePendingReferences(BGSSaveFormBuffer *);
    static void LoadPendingReferences(BGSLoadFormBuffer *);
    static void RevertPendingReferences(BGSLoadFormBuffer *);
    // static void InitActionList(TESObjectREFR*, ExtraDataList*);
    static void CopyReferencedObjectList(
        BSSimpleList<SCRIPT_REFERENCED_OBJECT *> *,
        BSSimpleList<SCRIPT_REFERENCED_OBJECT *> *,
        Script *
    );
    static void CopyVariableList(
        BSSimpleList<ScriptVariable *> *, BSSimpleList<ScriptVariable *> *, Script *
    );
    // static bool SetActionFlag(TESForm*, ExtraDataList*, unsigned int);
    static bool ParseParameters(
        const SCRIPT_PARAMETER *,
        const char *,
        unsigned int &,
        TESObjectREFR *,
        TESObjectREFR *,
        Script *,
        ScriptLocals *,
        ...
    );
    static bool GetValue(
        double &,
        const char *,
        unsigned int &,
        TESObjectREFR *,
        TESObjectREFR *,
        Script *,
        ScriptLocals *,
        bool
    );
    static void PutNumericIDInDouble(const unsigned int &, double &);
    static void GetNumericIDFromDouble(unsigned int &, const double &);
    TSCRIPTFUNC_GENERIC(UnimplementedFunction)
    TSCRIPTFUNC_GENERIC(MessageBoxFunction)
    static bool BuildMessageBoxStringFromParameters(
        const SCRIPT_PARAMETER *,
        const char *,
        TESObjectREFR *,
        TESObjectREFR *,
        Script *,
        ScriptLocals *,
        double &,
        unsigned int &,
        const char *,
        BSStringT<char> &
    );
    static bool BuildMessageBoxButtonsFromParameters(
        const SCRIPT_PARAMETER *,
        const char *,
        TESObjectREFR *,
        TESObjectREFR *,
        Script *,
        ScriptLocals *,
        double &,
        unsigned int &,
        BSStringT<char> *
    );
    static void HandleMessageMenu();
    TSCRIPTFUNC_GENERIC(MessageFunction)
    TSCRIPTFUNC_GENERIC(GetButtonPressedFunction)
    TSCRIPTFUNC_GENERIC(IsWaterObjectFunction)
    TSCRIPTFUNC_GENERIC(GetDistanceFunction)
    TSCRIPTFUNC_GENERIC(AddItemFunction)
    TSCRIPTFUNC_GENERIC(RemoveItemFunction)
    TSCRIPTFUNC_GENERIC(DropItemFunction)
    TSCRIPTFUNC_GENERIC(RemoveMeFunction)
    TSCRIPTFUNC_GENERIC(DropMeFunction)
    TSCRIPTFUNC_GENERIC(RemoveAllItemsFunction)
    TSCRIPTFUNC_GENERIC(RemoveAllTypedItemsFunction)
    TSCRIPTFUNC_GENERIC(OnFireFunction)
    TSCRIPTFUNC_GENERIC(OnNPCActivateFunction)
    TSCRIPTFUNC_GENERIC(OnActivateFunction)
    TSCRIPTFUNC_GENERIC(OnOpenFunction)
    TSCRIPTFUNC_GENERIC(OnCloseFunction)
    TSCRIPTFUNC_GENERIC(OnGrabFunction)
    TSCRIPTFUNC_GENERIC(OnDestructionStageChangeFunction)
    TSCRIPTFUNC_GENERIC(OnReleaseFunction)
    TSCRIPTFUNC_GENERIC(ActivateFunction)
    TSCRIPTFUNC_GENERIC(IsActionRefFunction)
    TSCRIPTFUNC_GENERIC(BugFunction)
    TSCRIPTFUNC_GENERIC(PlayerSpellBook)
    TSCRIPTFUNC_GENERIC(ToggleMapMarkersFunction)
    TSCRIPTFUNC_GENERIC(ToggleConversationStatsFunction)
    TSCRIPTFUNC_GENERIC(ToggleFullHelp)
    TSCRIPTFUNC_GENERIC(ToggleCombatStatsFunction)
    TSCRIPTFUNC_GENERIC(ToggleMagicStatsFunction)
    TSCRIPTFUNC_GENERIC(ToggleVerboseFunction)
    TSCRIPTFUNC_GENERIC(ToggleGodModeFunction)
    TSCRIPTFUNC_GENERIC(ToggleCollisionGeometryFunction)
    TSCRIPTFUNC_GENERIC(ToggleCharControllerShapeFunction)
    TSCRIPTFUNC_GENERIC(ToggleMaterialGeometryFunction)
    TSCRIPTFUNC_GENERIC(SaveWorldFunction)
    TSCRIPTFUNC_GENERIC(ToggleBordersFunction)
    TSCRIPTFUNC_GENERIC(ToggleProjectileDebugFunction)
    TSCRIPTFUNC_GENERIC(ToggleMenusFunction)
    TSCRIPTFUNC_GENERIC(ToggleSafeZoneFunction)
    TSCRIPTFUNC_GENERIC(ToggleSkyFunction)
    TSCRIPTFUNC_GENERIC(ToggleCollisionFunction)
    TSCRIPTFUNC_GENERIC(ToggleLeavesFunction)
    TSCRIPTFUNC_GENERIC(ToggleWireframeFunction)
    TSCRIPTFUNC_GENERIC(ToggleDebugTextFunction)
    TSCRIPTFUNC_GENERIC(SetDebugTextFunction)
    TSCRIPTFUNC_GENERIC(RunMemoryPass)
    TSCRIPTFUNC_GENERIC(ToggleLiteBriteFunction)
    TSCRIPTFUNC_GENERIC(ShowScenegraphFunction)
    TSCRIPTFUNC_GENERIC(ShowFullScenegraphFunction)
    TSCRIPTFUNC_GENERIC(ShowViewerStringsFunction)
    TSCRIPTFUNC_GENERIC(ToggleLODLandFunction)
    TSCRIPTFUNC_GENERIC(SetLODObjectDistanceFunction)
    TSCRIPTFUNC_GENERIC(SetTerminalMenuPosFunction)
    TSCRIPTFUNC_GENERIC(MovePipboyKnobFunction)
    TSCRIPTFUNC_GENERIC(HighlightBodyPartFunction)
    TSCRIPTFUNC_GENERIC(HighlightAdditionalReferenceFunction)
    TSCRIPTFUNC_GENERIC(DeactivateAllHighlightsFunction)
    TSCRIPTFUNC_GENERIC(TriggerHUDShudderFunction)
    TSCRIPTFUNC_GENERIC(HelpFunction)
    TSCRIPTFUNC_GENERIC(ToggleNavMeshFunction)
    TSCRIPTFUNC_GENERIC(TogglePathlinesFunction)
    TSCRIPTFUNC_GENERIC(DisableNavMesh)
    TSCRIPTFUNC_GENERIC(EnableNavMesh)
    TSCRIPTFUNC_GENERIC(PickRefByIDFunction)
    TSCRIPTFUNC_GENERIC(SetLightingPassesFunction)
    TSCRIPTFUNC_GENERIC(ToggleGrassUpdateFunction)
    TSCRIPTFUNC_GENERIC(SetFogDepthFunction)
    TSCRIPTFUNC_GENERIC(SetClipDistFunction)
    TSCRIPTFUNC_GENERIC(ToggleShadowVolumesFunction)
    TSCRIPTFUNC_GENERIC(SetImageSpaceGlowParamFunction)
    TSCRIPTFUNC_GENERIC(AddDecal)
    TSCRIPTFUNC_GENERIC(HairTint)
    TSCRIPTFUNC_GENERIC(ToggleAiDetection)
    TSCRIPTFUNC_GENERIC(ToggleAI)
    TSCRIPTFUNC_GENERIC(ShowHeadTrackTarget)
    TSCRIPTFUNC_GENERIC(ToggleHighProcess)
    TSCRIPTFUNC_GENERIC(ToggleLowProcess)
    TSCRIPTFUNC_GENERIC(ToggleMiddleLowProcess)
    TSCRIPTFUNC_GENERIC(ToggleMiddleHighProcess)
    TSCRIPTFUNC_GENERIC(ToggleAISchedules)
    TSCRIPTFUNC_GENERIC(SpeakSoundFunction)
    TSCRIPTFUNC_GENERIC(ToggleScriptsFunction)
    TSCRIPTFUNC_GENERIC(ToggleGrassFunction)
    TSCRIPTFUNC_GENERIC(RefreshINIFunction)
    TSCRIPTFUNC_GENERIC(ToggleEmotionsFunction)
    TSCRIPTFUNC_GENERIC(TestCode)
    TSCRIPTFUNC_GENERIC(TestDegradeFunction)
    TSCRIPTFUNC_GENERIC(PrintAILists)
    TSCRIPTFUNC_GENERIC(PrintNPCDialog)
    TSCRIPTFUNC_GENERIC(CenterOnCellFunction)
    TSCRIPTFUNC_GENERIC(CenterOnExteriorFunction)
    TSCRIPTFUNC_GENERIC(CenterOnWorldFunction)
    TSCRIPTFUNC_GENERIC(ToggleDialogSubtitle)
    TSCRIPTFUNC_GENERIC(ShowRenderPasses)
    TSCRIPTFUNC_GENERIC(FreezeRendererAccumulation)
    TSCRIPTFUNC_GENERIC(ToggleOcclusion)
    TSCRIPTFUNC_GENERIC(OutputMemContexts)
    TSCRIPTFUNC_GENERIC(ResetMemContexts)
    TSCRIPTFUNC_GENERIC(OutputMemStats)
    TSCRIPTFUNC_GENERIC(OutputMemStatsFullWalk)
    TSCRIPTFUNC_GENERIC(OutputTextureUseMap)
    TSCRIPTFUNC_GENERIC(OutputArchiveProfile)
    TSCRIPTFUNC_GENERIC(QuitGame)
    TSCRIPTFUNC_GENERIC(SaveIniFiles)
    TSCRIPTFUNC_GENERIC(PurgeCellBuffers)
    TSCRIPTFUNC_GENERIC(RevertWorld)
    TSCRIPTFUNC_GENERIC(ToggleDetectionStats)
    TSCRIPTFUNC_GENERIC(SetTargetRefraction)
    TSCRIPTFUNC_GENERIC(SetTargetFalloff)
    TSCRIPTFUNC_GENERIC(SetTargetDOF)
    TSCRIPTFUNC_GENERIC(ToggleFullScreenMotionBlur)
    TSCRIPTFUNC_GENERIC(SetMotionBlur)
    TSCRIPTFUNC_GENERIC(ToggleMotionBlur)
    TSCRIPTFUNC_GENERIC(ToggleFootIK)
    TSCRIPTFUNC_GENERIC(ToggleGrabIK)
    TSCRIPTFUNC_GENERIC(ToggleLookIK)
    TSCRIPTFUNC_GENERIC(ToggleRagdollAnim)
    TSCRIPTFUNC_GENERIC(DrawSkeleton)
    TSCRIPTFUNC_GENERIC(SetVelFunction)
    TSCRIPTFUNC_GENERIC(SetTargetRefractionFire)
    TSCRIPTFUNC_GENERIC(ToggleRefractionDebug)
    TSCRIPTFUNC_GENERIC(ToggleCombatAI)
    TSCRIPTFUNC_GENERIC(ToggleFlyCam)
    TSCRIPTFUNC_GENERIC(TogglePathingInfoFunction)
    TSCRIPTFUNC_GENERIC(SetUFOCamSpeedMult)
    TSCRIPTFUNC_GENERIC(ToggleTestLight)
    TSCRIPTFUNC_GENERIC(ToggleMultibound)
    TSCRIPTFUNC_GENERIC(AddOcclusionPlane)
    TSCRIPTFUNC_GENERIC(SetGlobalRadialBlur)
    TSCRIPTFUNC_GENERIC(ToggleBoundVisGeometry)
    TSCRIPTFUNC_GENERIC(ToggleEOFImageSpace)
    TSCRIPTFUNC_GENERIC(DumpMenuPackingInfo)
    TSCRIPTFUNC_GENERIC(HasLoaded3DFunction)
    TSCRIPTFUNC_GENERIC(GetActorValueFunction)
    TSCRIPTFUNC_GENERIC(GetPermanentActorValueFunction)
    TSCRIPTFUNC_GENERIC(GetBaseActorValueFunction)
    TSCRIPTFUNC_GENERIC(GetActorValueInfoFunction)
    TSCRIPTFUNC_GENERIC(SetActorValueFunction)
    TSCRIPTFUNC_GENERIC(SetSizeFunction)
    TSCRIPTFUNC_GENERIC(ModActorValueFunction)
    TSCRIPTFUNC_GENERIC(DamageActorValueFunction)
    TSCRIPTFUNC_GENERIC(RestoreActorValueFunction)
    TSCRIPTFUNC_GENERIC(GetGameSettingFunction)
    TSCRIPTFUNC_GENERIC(SetGameSettingFunction)
    TSCRIPTFUNC_GENERIC(GetINISettingFunction)
    TSCRIPTFUNC_GENERIC(SetINISettingFunction)
    TSCRIPTFUNC_GENERIC(ShowINISettingFunction)
    TSCRIPTFUNC_GENERIC(KillActorFunction)
    TSCRIPTFUNC_GENERIC(KillAllActorsFunction)
    TSCRIPTFUNC_GENERIC(ResurrectActorFunction)
    TSCRIPTFUNC_GENERIC(ForceActorValueFunction)
    TSCRIPTFUNC_GENERIC(RadioShutOffFunction)
    TSCRIPTFUNC_GENERIC(IsGoreDisabledFunction)
    TSCRIPTFUNC_GENERIC(GetActorsInHighFunction)
    TSCRIPTFUNC_GENERIC(ShowVarsFunction)
    TSCRIPTFUNC_GENERIC(ShowQuestVarsFunction)
    TSCRIPTFUNC_GENERIC(ShowQuestsFunction)
    TSCRIPTFUNC_GENERIC(ShowFunction)
    TSCRIPTFUNC_GENERIC(SetQuestObjectFunction)
    TSCRIPTFUNC_GENERIC(SetEssentialFunction)
    TSCRIPTFUNC_GENERIC(RotateFunction)
    TSCRIPTFUNC_GENERIC(GetPosFunction)
    TSCRIPTFUNC_GENERIC(SetPosFunction)
    TSCRIPTFUNC_GENERIC(GetStartingPosFunction)
    TSCRIPTFUNC_GENERIC(GetAngleFunction)
    TSCRIPTFUNC_GENERIC(GetStartingAngleFunction)
    TSCRIPTFUNC_GENERIC(SetAngleFunction)
    TSCRIPTFUNC_GENERIC(SetAtStartFunction)
    static void SetPosBase(TESObjectREFR *, char, float);
    static void SetAngleBase(TESObjectREFR *, char, float);
    static void SetScaleBase(TESObjectREFR *, float);
    static void SetRigidBodyMassBase(TESObjectREFR *, float);
    static void DamageObjectBase(TESObjectREFR *, float);
    static void MatchFaceGeometryBase(TESObjectREFR *, TESObjectREFR *, int);
    TSCRIPTFUNC_GENERIC(GetCurrentTimeFunction)
    TSCRIPTFUNC_GENERIC(GetSecondsPassedFunction)
    TSCRIPTFUNC_GENERIC(PlayGroupFunction)
    TSCRIPTFUNC_GENERIC(LoopGroupFunction)
    TSCRIPTFUNC_GENERIC(PlayExplosionFunction)
    TSCRIPTFUNC_GENERIC(SkipAnimFunction)
    TSCRIPTFUNC_GENERIC(StartCombatFunction)
    TSCRIPTFUNC_GENERIC(StopCombatFunction)
    TSCRIPTFUNC_GENERIC(StopCombatAlarmOnActorFunction)
    TSCRIPTFUNC_GENERIC(GetScaleFunction)
    TSCRIPTFUNC_GENERIC(SetScaleFunction)
    TSCRIPTFUNC_GENERIC(ModScaleFunction)
    TSCRIPTFUNC_GENERIC(GetLOSFunction)
    TSCRIPTFUNC_GENERIC(AddSpellFunction)
    TSCRIPTFUNC_GENERIC(RemoveSpellFunction)
    TSCRIPTFUNC_GENERIC(CastFunction)
    TSCRIPTFUNC_GENERIC(CastImmediateOnSelfFunction)
    TSCRIPTFUNC_GENERIC(DispelFunction)
    TSCRIPTFUNC_GENERIC(DispelAllSpellsFunction)
    TSCRIPTFUNC_GENERIC(PlaySoundFunction)
    TSCRIPTFUNC_GENERIC(PlaySound3DFunction)
    TSCRIPTFUNC_GENERIC(StreamMusicFunction)
    TSCRIPTFUNC_GENERIC(PlayMusicFunction)
    TSCRIPTFUNC_GENERIC(FadeSFXFunction)
    TSCRIPTFUNC_GENERIC(SetLocationSpecificLoadScreensOnlyFunction)
    TSCRIPTFUNC_GENERIC(CalcPathToPointFunction)
    TSCRIPTFUNC_GENERIC(CalcLowPathToPointFunction)
    TSCRIPTFUNC_GENERIC(ShowAnimFunction)
    TSCRIPTFUNC_GENERIC(Show1stPersonFunction)
    TSCRIPTFUNC_GENERIC(MenuModeFunction)
    TSCRIPTFUNC_GENERIC(GameModeFunction)
    TSCRIPTFUNC_GENERIC(ScriptEffectStartFunction)
    TSCRIPTFUNC_GENERIC(ScriptEffectFinishFunction)
    TSCRIPTFUNC_GENERIC(ScriptEffectUpdateFunction)
    TSCRIPTFUNC_GENERIC(ScriptEffectElapsedTimeFunction)
    TSCRIPTFUNC_GENERIC(EnableFunction)
    TSCRIPTFUNC_GENERIC(DisableFunction)
    TSCRIPTFUNC_GENERIC(GetDisabledFunction)
    TSCRIPTFUNC_GENERIC(GetLockedFunction)
    TSCRIPTFUNC_GENERIC(GetLockLevelFunction)
    TSCRIPTFUNC_GENERIC(GetIsLockBrokenFunction)
    TSCRIPTFUNC_GENERIC(DisableAllActors)
    TSCRIPTFUNC_GENERIC(GetIsFormTypeFunction)
    TSCRIPTFUNC_GENERIC(GetIsVoiceTypeFunction)
    TSCRIPTFUNC_GENERIC(PlaceAtMeFunction)
    TSCRIPTFUNC_GENERIC(SaveGame)
    TSCRIPTFUNC_GENERIC(LoadGame)
    TSCRIPTFUNC_GENERIC(Autosave)
    TSCRIPTFUNC_GENERIC(ForceSave)
    TSCRIPTFUNC_GENERIC(CopySaveGames)
    TSCRIPTFUNC_GENERIC(ExportBetaComment)
    TSCRIPTFUNC_GENERIC(ToggleCellNode)
    TSCRIPTFUNC_GENERIC(ToggleTrees)
    TSCRIPTFUNC_GENERIC(SetCameraFOV)
    TSCRIPTFUNC_GENERIC(ReloadShaders)
    TSCRIPTFUNC_GENERIC(DumpTexturePalette)
    TSCRIPTFUNC_GENERIC(DumpModelMap)
    TSCRIPTFUNC_GENERIC(SexChange)
    TSCRIPTFUNC_GENERIC(SetLastExtDoorActivated)
    TSCRIPTFUNC_GENERIC(GetDisease)
    TSCRIPTFUNC_GENERIC(GetVampire)
    TSCRIPTFUNC_GENERIC(GetClothingValue)
    TSCRIPTFUNC_GENERIC(SameFaction)
    TSCRIPTFUNC_GENERIC(SameRace)
    TSCRIPTFUNC_GENERIC(SameSex)
    TSCRIPTFUNC_GENERIC(SameFactionAsPC)
    TSCRIPTFUNC_GENERIC(SameRaceAsPC)
    TSCRIPTFUNC_GENERIC(SameSexAsPC)
    TSCRIPTFUNC_GENERIC(GetDetected)
    TSCRIPTFUNC_GENERIC(GetDead)
    TSCRIPTFUNC_GENERIC(GetItemCount)
    TSCRIPTFUNC_GENERIC(GetGold)
    TSCRIPTFUNC_GENERIC(GetSleeping)
    TSCRIPTFUNC_GENERIC(GetSitting)
    TSCRIPTFUNC_GENERIC(GetFurnitureMarkerID)
    TSCRIPTFUNC_GENERIC(IsCurrentFurnitureRef)
    TSCRIPTFUNC_GENERIC(IsCurrentFurnitureObj)
    TSCRIPTFUNC_GENERIC(GetTalkedToPC)
    TSCRIPTFUNC_GENERIC(GetTalkedToPCParam)
    TSCRIPTFUNC_GENERIC(GetQuestRunning)
    TSCRIPTFUNC_GENERIC(GetQuestCompleted)
    TSCRIPTFUNC_GENERIC(IgnoreRenderPass)
    TSCRIPTFUNC_GENERIC(GetStage)
    TSCRIPTFUNC_GENERIC(GetStageDone)
    TSCRIPTFUNC_GENERIC(StartQuestFunction)
    TSCRIPTFUNC_GENERIC(StopQuestFunction)
    TSCRIPTFUNC_GENERIC(SetStageFunction)
    TSCRIPTFUNC_GENERIC(GetFactionRankDifference)
    TSCRIPTFUNC_GENERIC(GetAlarmed)
    TSCRIPTFUNC_GENERIC(GetIsPleasant)
    TSCRIPTFUNC_GENERIC(GetIsCloudy)
    TSCRIPTFUNC_GENERIC(GetIsRaining)
    TSCRIPTFUNC_GENERIC(GetIsSnowing)
    TSCRIPTFUNC_GENERIC(GetWindSpeedFunction)
    TSCRIPTFUNC_GENERIC(GetWeatherPercentFunction)
    TSCRIPTFUNC_GENERIC(GetIsCurrentWeatherFunction)
    TSCRIPTFUNC_GENERIC(GetAttacked)
    TSCRIPTFUNC_GENERIC(GetIsCreature)
    TSCRIPTFUNC_GENERIC(GetShouldAttack)
    TSCRIPTFUNC_GENERIC(GetInCell)
    TSCRIPTFUNC_GENERIC(GetInCellParam)
    TSCRIPTFUNC_GENERIC(GetInWorldspace)
    TSCRIPTFUNC_GENERIC(SetCellPublicFunction)
    TSCRIPTFUNC_GENERIC(GetInSameCell)
    TSCRIPTFUNC_GENERIC(GetIsClass)
    TSCRIPTFUNC_GENERIC(GetIsRace)
    TSCRIPTFUNC_GENERIC(GetIsCreatureType)
    TSCRIPTFUNC_GENERIC(GetIsSex)
    TSCRIPTFUNC_GENERIC(GetIsPlayableRace)
    TSCRIPTFUNC_GENERIC(GetInFaction)
    TSCRIPTFUNC_GENERIC(GetPCIsClass)
    TSCRIPTFUNC_GENERIC(GetPCIsRace)
    TSCRIPTFUNC_GENERIC(GetPCIsSex)
    TSCRIPTFUNC_GENERIC(GetPCInFaction)
    TSCRIPTFUNC_GENERIC(GetIsID)
    TSCRIPTFUNC_GENERIC(GetIsChild)
    TSCRIPTFUNC_GENERIC(GetIsUsedItem)
    TSCRIPTFUNC_GENERIC(GetIsUsedItemType)
    TSCRIPTFUNC_GENERIC(GetUsedItemLevelFunction)
    TSCRIPTFUNC_GENERIC(GetUsedItemActivateFunction)
    TSCRIPTFUNC_GENERIC(IsInListFunction)
    TSCRIPTFUNC_GENERIC(MessageBoxIconFunction)
    TSCRIPTFUNC_GENERIC(GetIsRef)
    TSCRIPTFUNC_GENERIC(GetFactionRank)
    TSCRIPTFUNC_GENERIC(SetFactionRank)
    TSCRIPTFUNC_GENERIC(ModFactionRank)
    TSCRIPTFUNC_GENERIC(GetFactionReaction)
    TSCRIPTFUNC_GENERIC(SetFactionReaction)
    TSCRIPTFUNC_GENERIC(ModFactionReaction)
    TSCRIPTFUNC_GENERIC(TestAllCellsFunction)
    TSCRIPTFUNC_GENERIC(RenderTestCellFunction)
    TSCRIPTFUNC_GENERIC(RenderTestHereFunction)
    TSCRIPTFUNC_GENERIC(GetGlobalValue)
    TSCRIPTFUNC_GENERIC(GetDisposition)
    TSCRIPTFUNC_GENERIC(GetRandomPercent)
    TSCRIPTFUNC_GENERIC(GetLevel)
    TSCRIPTFUNC_GENERIC(GetArmorRating)
    TSCRIPTFUNC_GENERIC(GetDayOfWeekFunction)
    TSCRIPTFUNC_GENERIC(IsPCInJailFunction)
    TSCRIPTFUNC_GENERIC(ModDisposition)
    TSCRIPTFUNC_GENERIC(GetDeadCount)
    TSCRIPTFUNC_GENERIC(ShowMap)
    TSCRIPTFUNC_GENERIC(StartConversation)
    TSCRIPTFUNC_GENERIC(AddTopicFunction)
    TSCRIPTFUNC_GENERIC(SayFunction)
    TSCRIPTFUNC_GENERIC(SayToFunction)
    TSCRIPTFUNC_GENERIC(EvaluatePackageFunction)
    TSCRIPTFUNC_GENERIC(ResetAIFunction)
    TSCRIPTFUNC_GENERIC(SendAssaultAlarmFunction)
    TSCRIPTFUNC_GENERIC(ModPCMiscStat)
    TSCRIPTFUNC_GENERIC(GetPCMiscStat)
    TSCRIPTFUNC_GENERIC(SetAlertFunction)
    TSCRIPTFUNC_GENERIC(GetAlertFunction)
    TSCRIPTFUNC_GENERIC(LookFunction)
    TSCRIPTFUNC_GENERIC(StopLookFunction)
    TSCRIPTFUNC_GENERIC(SetSkyParamFunction)
    TSCRIPTFUNC_GENERIC(SetHDRParamFunction)
    TSCRIPTFUNC_GENERIC(PrintHDRParamFunction)
    TSCRIPTFUNC_GENERIC(ToggleHDRDebugFunction)
    TSCRIPTFUNC_GENERIC(ShowPivotFunction)
    static void
    CheckFlagFunction(unsigned int, TESObjectREFR *, TESForm *, ScriptLocals *, double &);
    TSCRIPTFUNC_GENERIC(OnAddFunction)
    TSCRIPTFUNC_GENERIC(OnEquipFunction)
    TSCRIPTFUNC_GENERIC(OnUnequipFunction)
    TSCRIPTFUNC_GENERIC(OnDropFunction)
    TSCRIPTFUNC_GENERIC(OnHitFunction)
    TSCRIPTFUNC_GENERIC(OnHitWithFunction)
    TSCRIPTFUNC_GENERIC(OnDeathFunction)
    TSCRIPTFUNC_GENERIC(OnMurderFunction)
    TSCRIPTFUNC_GENERIC(OnCombatEndFunction)
    TSCRIPTFUNC_GENERIC(OnPackageStartFunction)
    TSCRIPTFUNC_GENERIC(OnPackageEndFunction)
    TSCRIPTFUNC_GENERIC(OnPackageChangeFunction)
    TSCRIPTFUNC_GENERIC(OnLoadFunction)
    TSCRIPTFUNC_GENERIC(OnMagicEffectHitFunction)
    TSCRIPTFUNC_GENERIC(OnSellFunction)
    TSCRIPTFUNC_GENERIC(OnTriggerFunction)
    TSCRIPTFUNC_GENERIC(OnTriggerEnterFunction)
    TSCRIPTFUNC_GENERIC(OnTriggerLeaveFunction)
    TSCRIPTFUNC_GENERIC(OnStartCombatFunction)
    TSCRIPTFUNC_GENERIC(ActorOnEquipFunction)
    TSCRIPTFUNC_GENERIC(ActorOnUnequipFunction)
    TSCRIPTFUNC_GENERIC(OnResetFunction)
    TSCRIPTFUNC_GENERIC(OnSayToDoneFunction)
    TSCRIPTFUNC_GENERIC(EnablePlayerControlsFunction)
    TSCRIPTFUNC_GENERIC(DisablePlayerControlsFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerControlsDisabledFunction)
    TSCRIPTFUNC_GENERIC(GetHeadingAngleFunction)
    TSCRIPTFUNC_GENERIC(IsWeaponOutFunction)
    TSCRIPTFUNC_GENERIC(IsWeaponInListFunction)
    TSCRIPTFUNC_GENERIC(PickIdleFunction)
    TSCRIPTFUNC_GENERIC(PlayIdleFunction)
    TSCRIPTFUNC_GENERIC(PlayVATSCamerasFunction)
    TSCRIPTFUNC_GENERIC(IsTorchOutFunction)
    TSCRIPTFUNC_GENERIC(IsShieldOutFunction)
    TSCRIPTFUNC_GENERIC(IsFacingUpFunction)
    TSCRIPTFUNC_GENERIC(IsLeftUpFunction)
    TSCRIPTFUNC_GENERIC(GetKnockedStateFunction)
    TSCRIPTFUNC_GENERIC(GetWeaponAnimTypeFunction)
    TSCRIPTFUNC_GENERIC(IsWeaponSkillTypeFunction)
    TSCRIPTFUNC_GENERIC(GetCurrentAIPackageFunction)
    TSCRIPTFUNC_GENERIC(IsWaitingFunction)
    TSCRIPTFUNC_GENERIC(IsIdlePlayingFunction)
    TSCRIPTFUNC_GENERIC(IsTalkingFunction)
    TSCRIPTFUNC_GENERIC(GetWalkSpeedFunction)
    TSCRIPTFUNC_GENERIC(ShowQuestLogFunction)
    TSCRIPTFUNC_GENERIC(ShowFullQuestLogFunction)
    TSCRIPTFUNC_GENERIC(CompleteQuestFunction)
    TSCRIPTFUNC_GENERIC(ShowQuestTargetsFunction)
    TSCRIPTFUNC_GENERIC(LockFunction)
    TSCRIPTFUNC_GENERIC(UnlockFunction)
    TSCRIPTFUNC_GENERIC(GetCrimeFunction)
    TSCRIPTFUNC_GENERIC(GetCrimeKnownFunction)
    TSCRIPTFUNC_GENERIC(IsGuard)
    TSCRIPTFUNC_GENERIC(GetFatiguePercentageFunction)
    TSCRIPTFUNC_GENERIC(GetHealthPercentageFunction)
    TSCRIPTFUNC_GENERIC(GetCurrentAIProcedureFunction)
    TSCRIPTFUNC_GENERIC(GetTrespassWarningLevelFunction)
    TSCRIPTFUNC_GENERIC(IsTrespassingFunction)
    TSCRIPTFUNC_GENERIC(IsInMyOwnedCellFunction)
    TSCRIPTFUNC_GENERIC(IsContinuingPackagePCNearFunction)
    TSCRIPTFUNC_GENERIC(AddScriptPackageFunction)
    TSCRIPTFUNC_GENERIC(RemoveScriptPackageFunction)
    TSCRIPTFUNC_GENERIC(CanHaveFlamesFunction)
    TSCRIPTFUNC_GENERIC(HasFlamesFunction)
    TSCRIPTFUNC_GENERIC(AddFlamesFunction)
    TSCRIPTFUNC_GENERIC(RemoveFlamesFunction)
    TSCRIPTFUNC_GENERIC(GetOpenStateFunction)
    TSCRIPTFUNC_GENERIC(MoveToFunction)
    TSCRIPTFUNC_GENERIC(MoveToQuestTargetFunction)
    static void MoveToFunctionBase(TESObjectREFR *, TESObjectREFR *, float, float, float);
    TSCRIPTFUNC_GENERIC(MoveToFadeFunction)
    TSCRIPTFUNC_GENERIC(GetIsCurrentPackageFunction)
    TSCRIPTFUNC_GENERIC(AddFaceAnimNoteFunction)
    TSCRIPTFUNC_GENERIC(WakeUpPCFunction)
    TSCRIPTFUNC_GENERIC(IsPCSleepingFunction)
    TSCRIPTFUNC_GENERIC(IsPCAMurdererFunction)
    TSCRIPTFUNC_GENERIC(SetCombatStyleFunction)
    TSCRIPTFUNC_GENERIC(SelectPlayerSpellFunction)
    TSCRIPTFUNC_GENERIC(GetDetectionLevelFunction)
    TSCRIPTFUNC_GENERIC(IsActorDetected)
    TSCRIPTFUNC_GENERIC(GetEquippedFunction)
    TSCRIPTFUNC_GENERIC(WaitFunction)
    TSCRIPTFUNC_GENERIC(StopWaitingFunction)
    TSCRIPTFUNC_GENERIC(IsSwimming)
    TSCRIPTFUNC_GENERIC(GetPlayerSleepHours)
    TSCRIPTFUNC_GENERIC(SetPlayerSleepHours)
    TSCRIPTFUNC_GENERIC(GetAmountStolenSoldFunction)
    TSCRIPTFUNC_GENERIC(ModAmountStolenSoldFunction)
    TSCRIPTFUNC_GENERIC(GetPCExpelledFunction)
    TSCRIPTFUNC_GENERIC(SetPCExpelledFunction)
    TSCRIPTFUNC_GENERIC(GetPCFactionMurderFunction)
    TSCRIPTFUNC_GENERIC(SetPCFactionMurderFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerEnemyofFactionFunction)
    TSCRIPTFUNC_GENERIC(SetPlayerEnemyofFactionFunction)
    TSCRIPTFUNC_GENERIC(GetPCFactionAttackFunction)
    TSCRIPTFUNC_GENERIC(SetPCFactionAttackFunction)
    TSCRIPTFUNC_GENERIC(GetDestroyedFunction)
    TSCRIPTFUNC_GENERIC(SetDestroyedFunction)
    TSCRIPTFUNC_GENERIC(GetActionRefFunction)
    TSCRIPTFUNC_GENERIC(GetSelfFunction)
    TSCRIPTFUNC_GENERIC(GetContainerFunction)
    TSCRIPTFUNC_GENERIC(GetCombatTargetFunction)
    TSCRIPTFUNC_GENERIC(GetPackageTargetFunction)
    TSCRIPTFUNC_GENERIC(GetParentRefFunction)
    TSCRIPTFUNC_GENERIC(GetLinkedRefFunction)
    TSCRIPTFUNC_GENERIC(GetForceRun)
    TSCRIPTFUNC_GENERIC(SetForceRun)
    TSCRIPTFUNC_GENERIC(GetForceSneak)
    TSCRIPTFUNC_GENERIC(SetForceSneak)
    TSCRIPTFUNC_GENERIC(AdvanceLevelFunction)
    TSCRIPTFUNC_GENERIC(HasMagicEffectFunction)
    TSCRIPTFUNC_GENERIC(IsSpellTargetFunction)
    TSCRIPTFUNC_GENERIC(GetSpellUsageNumberFunction)
    TSCRIPTFUNC_GENERIC(GetVATSModeFunction)
    TSCRIPTFUNC_GENERIC(GetVATSTargetHeightFunction)
    TSCRIPTFUNC_GENERIC(GetDefaultOpenFunction)
    TSCRIPTFUNC_GENERIC(SetDefaultOpenFunction)
    TSCRIPTFUNC_GENERIC(SetOpenStateFunction)
    TSCRIPTFUNC_GENERIC(ShowClassMenu)
    TSCRIPTFUNC_GENERIC(ShowRaceMenu)
    TSCRIPTFUNC_GENERIC(ShowBarberMenu)
    TSCRIPTFUNC_GENERIC(ShowPlasticSurgeonMenu)
    TSCRIPTFUNC_GENERIC(ShowNameMenu)
    TSCRIPTFUNC_GENERIC(ShowBarterMenu)
    TSCRIPTFUNC_GENERIC(ShowSurgeryMenu)
    TSCRIPTFUNC_GENERIC(ShowHackingMiniGame)
    TSCRIPTFUNC_GENERIC(ShowComputersInterface)
    TSCRIPTFUNC_GENERIC(ShowRepairMenuFunction)
    TSCRIPTFUNC_GENERIC(ShowTraitMenu)
    TSCRIPTFUNC_GENERIC(GetPersuasionNumberFunction)
    TSCRIPTFUNC_GENERIC(GetTotalPersuasionNumberFunction)
    TSCRIPTFUNC_GENERIC(GetSandmanFunction)
    TSCRIPTFUNC_GENERIC(GetCannibalFunction)
    TSCRIPTFUNC_GENERIC(GetIsClassDefaultFunction)
    TSCRIPTFUNC_GENERIC(GetIsMyClassDefaultFunction)
    TSCRIPTFUNC_GENERIC(ReloadCurrentClimate)
    TSCRIPTFUNC_GENERIC(ReloadCurrentWeather)
    TSCRIPTFUNC_GENERIC(TestSeenData)
    TSCRIPTFUNC_GENERIC(TestLocalMap)
    TSCRIPTFUNC_GENERIC(SetChargenValue)
    TSCRIPTFUNC_GENERIC(ShowSpellmakingMenu)
    TSCRIPTFUNC_GENERIC(SetGhostFunction)
    TSCRIPTFUNC_GENERIC(GetGhostFunction)
    TSCRIPTFUNC_GENERIC(EquipItemFunction)
    TSCRIPTFUNC_GENERIC(UnEquipItemFunction)
    TSCRIPTFUNC_GENERIC(SetClassFunction)
    TSCRIPTFUNC_GENERIC(SetUnconsciousFunction)
    TSCRIPTFUNC_GENERIC(GetUnconsciousFunction)
    TSCRIPTFUNC_GENERIC(SetRestrainedFunction)
    TSCRIPTFUNC_GENERIC(GetRestrainedFunction)
    TSCRIPTFUNC_GENERIC(ForceFleeFunction)
    TSCRIPTFUNC_GENERIC(ForceTakeCoverFunction)
    TSCRIPTFUNC_GENERIC(GetOffersServiceNowFunction)
    TSCRIPTFUNC_GENERIC(SetActiveWeather)
    TSCRIPTFUNC_GENERIC(ReleaseWeatherOverride)
    TSCRIPTFUNC_GENERIC(ModBarterGoldFunction)
    TSCRIPTFUNC_GENERIC(SetBarterGoldFunction)
    TSCRIPTFUNC_GENERIC(GetBarterGoldFunction)
    TSCRIPTFUNC_GENERIC(IsTimePassingFunction)
    TSCRIPTFUNC_GENERIC(TrapUpdateFunction)
    TSCRIPTFUNC_GENERIC(ModPCSkillFunction)
    TSCRIPTFUNC_GENERIC(ModPCAttributeFunction)
    TSCRIPTFUNC_GENERIC(SetCanPCFastTravelFunction)
    TSCRIPTFUNC_GENERIC(GetArmorRatingUpperFunction)
    TSCRIPTFUNC_GENERIC(GetOwnershipFunction)
    TSCRIPTFUNC_GENERIC(SetOwnershipFunction)
    TSCRIPTFUNC_GENERIC(GetCellOwnershipFunction)
    TSCRIPTFUNC_GENERIC(SetCellOwnershipFunction)
    TSCRIPTFUNC_GENERIC(IsHorseStolenFunction)
    TSCRIPTFUNC_GENERIC(SetCellFullNameFunction)
    TSCRIPTFUNC_GENERIC(SetActorFullNameFunction)
    TSCRIPTFUNC_GENERIC(IsSneakingFunction)
    TSCRIPTFUNC_GENERIC(IsRunningFunction)
    TSCRIPTFUNC_GENERIC(GetFriendHitFunction)
    TSCRIPTFUNC_GENERIC(IsInCombatFunction)
    TSCRIPTFUNC_GENERIC(SetPackageDurationFunction)
    TSCRIPTFUNC_GENERIC(PlayMagicShader)
    TSCRIPTFUNC_GENERIC(PlayMagicEffect)
    TSCRIPTFUNC_GENERIC(StopMagicShader)
    TSCRIPTFUNC_GENERIC(StopMagicEffect)
    TSCRIPTFUNC_GENERIC(PreloadMagicEffect)
    TSCRIPTFUNC_GENERIC(SetActorAlpha)
    TSCRIPTFUNC_GENERIC(ResetCellFunction)
    TSCRIPTFUNC_GENERIC(IsAnimPlayingFunction)
    TSCRIPTFUNC_GENERIC(EnableLinkedPathPointsFunction)
    TSCRIPTFUNC_GENERIC(DisableLinkedPathPointsFunction)
    TSCRIPTFUNC_GENERIC(IsInInteriorFunction)
    TSCRIPTFUNC_GENERIC(PlayBinkFunction)
    TSCRIPTFUNC_GENERIC(ForceWeather)
    TSCRIPTFUNC_GENERIC(ToggleActorAI)
    TSCRIPTFUNC_GENERIC(IsActorsAIOff)
    TSCRIPTFUNC_GENERIC(SetAllReachable)
    TSCRIPTFUNC_GENERIC(SetAllVisible)
    TSCRIPTFUNC_GENERIC(SetNoAvoidance)
    TSCRIPTFUNC_GENERIC(IsActorUsingATorchFunction)
    TSCRIPTFUNC_GENERIC(SetLevelFunction)
    TSCRIPTFUNC_GENERIC(ResetFallDamageTimerFunction)
    TSCRIPTFUNC_GENERIC(IsXBoxFunction)
    TSCRIPTFUNC_GENERIC(IsPS3Function)
    TSCRIPTFUNC_GENERIC(IsPCFunction)
    TSCRIPTFUNC_GENERIC(DamageWeaponFunction)
    TSCRIPTFUNC_GENERIC(GetWeaponHealthFunction)
    TSCRIPTFUNC_GENERIC(IsActorEvilFunction)
    TSCRIPTFUNC_GENERIC(IsActorVictimFunction)
    TSCRIPTFUNC_GENERIC(GetIdleDoneOnceFunction)
    TSCRIPTFUNC_GENERIC(GetNoRumorsFunction)
    TSCRIPTFUNC_GENERIC(SetNoRumorsFunction)
    TSCRIPTFUNC_GENERIC(GetWhichServiceFunction)
    TSCRIPTFUNC_GENERIC(TriggerHitShaderFunction)
    TSCRIPTFUNC_GENERIC(ToggleWaterSystem)
    TSCRIPTFUNC_GENERIC(ToggleWaterRadius)
    TSCRIPTFUNC_GENERIC(ModifyWaterShader)
    TSCRIPTFUNC_GENERIC(ModifyWaterShaderShallowColor)
    TSCRIPTFUNC_GENERIC(ModifyWaterShaderDeepColor)
    TSCRIPTFUNC_GENERIC(ModifyWaterShaderReflectionColor)
    TSCRIPTFUNC_GENERIC(ShowWhoDetectsPlayer)
    TSCRIPTFUNC_GENERIC(Reset3DStateFunction)
    TSCRIPTFUNC_GENERIC(IsActorRidingHorseFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerHasLastRiddenHorseFunction)
    TSCRIPTFUNC_GENERIC(AddAchievement)
    TSCRIPTFUNC_GENERIC(SetRigidBodyMass)
    TSCRIPTFUNC_GENERIC(DuplicateAllItemsFunction)
    TSCRIPTFUNC_GENERIC(IsInDangerousWaterFunction)
    TSCRIPTFUNC_GENERIC(EssentailDeathReloadFunction)
    TSCRIPTFUNC_GENERIC(BeginTrace)
    TSCRIPTFUNC_GENERIC(SetShowQuestItemsFunction)
    TSCRIPTFUNC_GENERIC(DuplicateNPCStatsFunction)
    TSCRIPTFUNC_GENERIC(ResetHealthFunction)
    TSCRIPTFUNC_GENERIC(GetIgnoreFriendlyHitsFunction)
    TSCRIPTFUNC_GENERIC(SetIgnoreFriendlyHitsFunction)
    TSCRIPTFUNC_GENERIC(IsPlayersLastRiddenHorseFunction)
    TSCRIPTFUNC_GENERIC(SetActorRefractionFunction)
    TSCRIPTFUNC_GENERIC(RunCellTest)
    TSCRIPTFUNC_GENERIC(SetItemValueFunction)
    TSCRIPTFUNC_GENERIC(StartAllQuests)
    TSCRIPTFUNC_GENERIC(CompleteAllQuestStages)
    TSCRIPTFUNC_GENERIC(FlushPersistantActors)
    TSCRIPTFUNC_GENERIC(DeleteReference)
    TSCRIPTFUNC_GENERIC(ToggleFogOfWar)
    TSCRIPTFUNC_GENERIC(OutputLocalMapPictures)
    TSCRIPTFUNC_GENERIC(SendCrimeAlarmFunction)
    TSCRIPTFUNC_GENERIC(SetSceneIsComplex)
    TSCRIPTFUNC_GENERIC(SetGamma)
    TSCRIPTFUNC_GENERIC(WasteMemory)
    TSCRIPTFUNC_GENERIC(ClearAdaptedLight)
    TSCRIPTFUNC_GENERIC(ToggleCastShadows)
    TSCRIPTFUNC_GENERIC(SetHUDGlowConstants)
    TSCRIPTFUNC_GENERIC(SetTreeMipmapBias)
    TSCRIPTFUNC_GENERIC(ForceCloseFile)
    TSCRIPTFUNC_GENERIC(StartMasterFileSeekData)
    TSCRIPTFUNC_GENERIC(DumpMasterFileSeekData)
    TSCRIPTFUNC_GENERIC(IsEssentialFunction)
    TSCRIPTFUNC_GENERIC(IsActorFunction)
    TSCRIPTFUNC_GENERIC(IsPlayerMovingIntoNewSpaceFunction)
    TSCRIPTFUNC_GENERIC(CreateFullCopyFunction)
    TSCRIPTFUNC_GENERIC(DeleteFullCopyFunction)
    TSCRIPTFUNC_GENERIC(GetTimeDeadFunction)
    TSCRIPTFUNC_GENERIC(DamageObjectFunction)
    TSCRIPTFUNC_GENERIC(GetLastPlayerActionFunction)
    TSCRIPTFUNC_GENERIC(IsPlayerActionActiveFunction)
    TSCRIPTFUNC_GENERIC(SetTalkingActivatorActorFunction)
    TSCRIPTFUNC_GENERIC(GetTalkingActivatorActorFunction)
    TSCRIPTFUNC_GENERIC(IsActorTalkingThroughActivatorFunction)
    TSCRIPTFUNC_GENERIC(RewardExperiencePointsFunction)
    TSCRIPTFUNC_GENERIC(AddPerkFunction)
    TSCRIPTFUNC_GENERIC(RemovePerkFunction)
    TSCRIPTFUNC_GENERIC(HasPerkFunction)
    TSCRIPTFUNC_GENERIC(SetAllyFunction)
    TSCRIPTFUNC_GENERIC(SetEnemyFunction)
    TSCRIPTFUNC_GENERIC(AddNoteFunction)
    TSCRIPTFUNC_GENERIC(RemoveNoteFunction)
    TSCRIPTFUNC_GENERIC(GetHasNoteFunction)
    TSCRIPTFUNC_GENERIC(AddFactionFunction)
    TSCRIPTFUNC_GENERIC(RemoveFactionFunction)
    TSCRIPTFUNC_GENERIC(SetDispositionFunction)
    TSCRIPTFUNC_GENERIC(SetDepthOfField)
    TSCRIPTFUNC_GENERIC(SetDepthOfFieldRange)
    TSCRIPTFUNC_GENERIC(SetGlobalTimeMultiplierFunction)
    TSCRIPTFUNC_GENERIC(GetHitLocationFunction)
    TSCRIPTFUNC_GENERIC(IsPC1stPersonFunction)
    TSCRIPTFUNC_GENERIC(SetActorsAIFunction)
    TSCRIPTFUNC_GENERIC(ClearOwnershipFunction)
    TSCRIPTFUNC_GENERIC(PushActorAwayFunction)
    TSCRIPTFUNC_GENERIC(GetCauseofDeathFunction)
    TSCRIPTFUNC_GENERIC(IsLimbGoneFunction)
    TSCRIPTFUNC_GENERIC(GetKillingBlowLimbFunction)
    TSCRIPTFUNC_GENERIC(ApplyImageSpaceModifier)
    TSCRIPTFUNC_GENERIC(RemoveImageSpaceModifier)
    TSCRIPTFUNC_GENERIC(HasFriendDispositionFunction)
    TSCRIPTFUNC_GENERIC(FriendDispositionBoostFunction)
    TSCRIPTFUNC_GENERIC(SetCellImageSpace)
    TSCRIPTFUNC_GENERIC(SetImageSpace)
    TSCRIPTFUNC_GENERIC(ShowCharGenMenu)
    TSCRIPTFUNC_GENERIC(ShowLockpickMenu)
    TSCRIPTFUNC_GENERIC(SetSPECIALPoints)
    TSCRIPTFUNC_GENERIC(AddSPECIALPoints)
    TSCRIPTFUNC_GENERIC(SetTagSkills)
    TSCRIPTFUNC_GENERIC(AddTagSkills)
    TSCRIPTFUNC_GENERIC(ShowLockpickMenuDebug)
    TSCRIPTFUNC_GENERIC(GetKillerFunction)
    TSCRIPTFUNC_GENERIC(GetKillerObjectFunction)
    TSCRIPTFUNC_GENERIC(GetFactionCombatReactionFunction)
    TSCRIPTFUNC_GENERIC(GetIsMovingFunction)
    TSCRIPTFUNC_GENERIC(GetIsTurningFunction)
    TSCRIPTFUNC_GENERIC(GetAnimActionFunction)
    TSCRIPTFUNC_GENERIC(UseWeaponFunction)
    TSCRIPTFUNC_GENERIC(EvaluateSpellConditionsFunction)
    TSCRIPTFUNC_GENERIC(SendSherlockDebugPage)
    TSCRIPTFUNC_GENERIC(DebugCombatPlanFunction)
    TSCRIPTFUNC_GENERIC(SetCombatActionCostFunction)
    TSCRIPTFUNC_GENERIC(ToggleCombatDebugFunction)
    TSCRIPTFUNC_GENERIC(ForceCombatGroupStrategyFunction)
    TSCRIPTFUNC_GENERIC(PlaceLocationMarkerFunction)
    TSCRIPTFUNC_GENERIC(ClearLocationMarkersFunction)
    TSCRIPTFUNC_GENERIC(ShowInventoryFunction)
    TSCRIPTFUNC_GENERIC(ResetPerformanceTimers)
    TSCRIPTFUNC_GENERIC(ToggleDecalDebug)
    TSCRIPTFUNC_GENERIC(ToggleDecalRendering)
    TSCRIPTFUNC_GENERIC(SetImageSpaceModifiersEnable)
    TSCRIPTFUNC_GENERIC(ExistsFunction)
    TSCRIPTFUNC_GENERIC(GetGroupMemberCountFunction)
    TSCRIPTFUNC_GENERIC(GetGroupTargetCountFunction)
    TSCRIPTFUNC_GENERIC(SetObjectiveCompletedFunction)
    TSCRIPTFUNC_GENERIC(SetObjectiveDisplayedFunction)
    TSCRIPTFUNC_GENERIC(GetObjectiveCompletedFunction)
    TSCRIPTFUNC_GENERIC(GetObjectiveDisplayedFunction)
    TSCRIPTFUNC_GENERIC(GetPlantedExplosiveFunction)
    TSCRIPTFUNC_GENERIC(CompleteAllObjectivesFunction)
    TSCRIPTFUNC_GENERIC(TogglePrimitivesFunction)
    TSCRIPTFUNC_GENERIC(GetIsObjectTypeFunction)
    TSCRIPTFUNC_GENERIC(GetDialogueEmotionFunction)
    TSCRIPTFUNC_GENERIC(GetDialogueEmotionValueFunction)
    TSCRIPTFUNC_GENERIC(ToggleVATSLight)
    TSCRIPTFUNC_GENERIC(TriggerScreenBlood)
    TSCRIPTFUNC_GENERIC(ClearScreenBlood)
    TSCRIPTFUNC_GENERIC(ToggleScreenBloodTest)
    TSCRIPTFUNC_GENERIC(TriggerScreenSplatter)
    TSCRIPTFUNC_GENERIC(ClearScreenSplatter)
    TSCRIPTFUNC_GENERIC(SetScreenSplatterTexture)
    TSCRIPTFUNC_GENERIC(SetScreenSplatterFade)
    TSCRIPTFUNC_GENERIC(ResetDialogueFlags)
    TSCRIPTFUNC_GENERIC(ResetAllTerminals)
    TSCRIPTFUNC_GENERIC(SetAudioMultiThreading)
    TSCRIPTFUNC_GENERIC(RemoveMerchantContainer)
    TSCRIPTFUNC_GENERIC(SetMerchantContainer)
    TSCRIPTFUNC_GENERIC(ShowWarningFunction)
    TSCRIPTFUNC_GENERIC(TriggerEnterFunction)
    TSCRIPTFUNC_GENERIC(MarkForDeleteFunction)
    TSCRIPTFUNC_GENERIC(AddItemHealthPercentFunction)
    TSCRIPTFUNC_GENERIC(PlaceAtMeHealthPercentFunction)
    TSCRIPTFUNC_GENERIC(CloseAllMenusFunction)
    static TESObjectREFR *
    PlaceAtMeFunctionBase(TESObjectREFR *, TESObject *, int, int, int, float);
    TSCRIPTFUNC_GENERIC(PipboyRadio)
    TSCRIPTFUNC_GENERIC(SetNPCRadio)
    TSCRIPTFUNC_GENERIC(SetBroadcastState)
    TSCRIPTFUNC_GENERIC(GetBroadcastState)
    TSCRIPTFUNC_GENERIC(StartRadioConversation)
    TSCRIPTFUNC_GENERIC(ForceRadioStationUpdateFunction)
    TSCRIPTFUNC_GENERIC(ExitGame)
    TSCRIPTFUNC_GENERIC(GetInZoneFunction)
    TSCRIPTFUNC_GENERIC(GetFactionRelationFunction)
    TSCRIPTFUNC_GENERIC(IsLastPlayedIdleFunction)
    TSCRIPTFUNC_GENERIC(SetPlayerTeammateFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerTeammateFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerTeammateCountFunction)
    TSCRIPTFUNC_GENERIC(OpenTeammateContainerFunction)
    TSCRIPTFUNC_GENERIC(ClearFactionPlayerEnemyFunction)
    TSCRIPTFUNC_GENERIC(ClearActorsFactionsPlayerEnemyFunction)
    TSCRIPTFUNC_GENERIC(GetActorCrimePlayerEnemyFunction)
    TSCRIPTFUNC_GENERIC(GetActorFactionPlayerEnemyFunction)
    TSCRIPTFUNC_GENERIC(GetMinorCrimeCountFunction)
    TSCRIPTFUNC_GENERIC(GetMajorCrimeCountFunction)
    TSCRIPTFUNC_GENERIC(SetPlayerTagSkillFunction)
    TSCRIPTFUNC_GENERIC(IsPlayerTagSkillFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerGrabbedRefFunction)
    TSCRIPTFUNC_GENERIC(IsPlayerGrabbedRefFunction)
    TSCRIPTFUNC_GENERIC(PlaceLeveledActorAtMeFunction)
    TSCRIPTFUNC_GENERIC(GetDestructionStageFunction)
    TSCRIPTFUNC_GENERIC(ClearDestructionFunction)
    TSCRIPTFUNC_GENERIC(GetAggroRadiusViolatedFunction)
    TSCRIPTFUNC_GENERIC(GetIsAlignmentFunction)
    TSCRIPTFUNC_GENERIC(ResetQuestFunction)
    TSCRIPTFUNC_GENERIC(SetQuestDelayFunction)
    TSCRIPTFUNC_GENERIC(ForceActiveQuestFunction)
    TSCRIPTFUNC_GENERIC(GetThreatRatioFunction)
    TSCRIPTFUNC_GENERIC(MatchFaceGeometryFunction)
    TSCRIPTFUNC_GENERIC(GetIsUsedItemEquipTypeFunction)
    TSCRIPTFUNC_GENERIC(GetPlayerName)
    TSCRIPTFUNC_GENERIC(FireWeaponFunction)
    TSCRIPTFUNC_GENERIC(ShowTutorialMenu)
    TSCRIPTFUNC_GENERIC(AgeRaceFunction)
    TSCRIPTFUNC_GENERIC(MatchRaceFunction)
    TSCRIPTFUNC_GENERIC(SetPCYoungFunction)
    TSCRIPTFUNC_GENERIC(SetPCToddlerFunction)
    TSCRIPTFUNC_GENERIC(ToggleActorMover)
    TSCRIPTFUNC_GENERIC(ShowSPECIALBookMenu)
    TSCRIPTFUNC_GENERIC(ShowLoveTesterMenu)
    TSCRIPTFUNC_GENERIC(ShowTraitSelectMenu)
    TSCRIPTFUNC_GENERIC(ShowSlotMachineMenu)
    TSCRIPTFUNC_GENERIC(ShowBlackJackMenu)
    TSCRIPTFUNC_GENERIC(ShowRouletteMenu)
    TSCRIPTFUNC_GENERIC(ShowCaravanMenu)
    TSCRIPTFUNC_GENERIC(AddCardToPlayer)
    TSCRIPTFUNC_GENERIC(IsPlayerInRegion)
    TSCRIPTFUNC_GENERIC(SetCasinoCheatLevel)
    TSCRIPTFUNC_GENERIC(GetConcussedFunction)
    TSCRIPTFUNC_GENERIC(SetZoneRespawnsFunction)
    TSCRIPTFUNC_GENERIC(SetVATSTargetFunction)
    TSCRIPTFUNC_GENERIC(GetMapMarkerVisibleFunction)
    TSCRIPTFUNC_GENERIC(ResetInventoryFunction)
    TSCRIPTFUNC_GENERIC(TriggerLODApocalypseFunction)
    TSCRIPTFUNC_GENERIC(CreateDetectionEventFunction)
    TSCRIPTFUNC_GENERIC(GetWeaponHealthPercFunction)
    TSCRIPTFUNC_GENERIC(SetWeaponHealthPercFunction)
    TSCRIPTFUNC_GENERIC(ModWeaponHealthPercFunction)
    TSCRIPTFUNC_GENERIC(GetRadiationLevelFunction)
    TSCRIPTFUNC_GENERIC(ShowCharGenMenuModValues)
    TSCRIPTFUNC_GENERIC(SetRumbleFunction)
    TSCRIPTFUNC_GENERIC(SetNoActivationSound)
    TSCRIPTFUNC_GENERIC(ClearNoActivationSound)
    TSCRIPTFUNC_GENERIC(IsGreetingPlayerFunction)
    TSCRIPTFUNC_GENERIC(StartSandmanFunction)
    TSCRIPTFUNC_GENERIC(StartCannibalFunction)
    TSCRIPTFUNC_GENERIC(HasBeenEatenFunction)
    TSCRIPTFUNC_GENERIC(IgnoreCrimeFunction)
    TSCRIPTFUNC_GENERIC(GetIgnoreCrimeFunction)
    TSCRIPTFUNC_GENERIC(GetLastHitCriticalFunction)
    TSCRIPTFUNC_GENERIC(ResetPipboyManagerFunction)
    TSCRIPTFUNC_GENERIC(IsCombatTargetFunction)
    TSCRIPTFUNC_GENERIC(RewardKarmaFunction)
    TSCRIPTFUNC_GENERIC(GetVATSRightAreaFreeFunction)
    TSCRIPTFUNC_GENERIC(GetVATSLeftAreaFreeFunction)
    TSCRIPTFUNC_GENERIC(GetVATSFrontAreaFreeFunction)
    TSCRIPTFUNC_GENERIC(GetVATSBackAreaFreeFunction)
    TSCRIPTFUNC_GENERIC(GetVATSRightTargetVisibleFunction)
    TSCRIPTFUNC_GENERIC(GetVATSLeftTargetVisibleFunction)
    TSCRIPTFUNC_GENERIC(GetVATSFrontTargetVisibleFunction)
    TSCRIPTFUNC_GENERIC(GetVATSBackTargetVisibleFunction)
    TSCRIPTFUNC_GENERIC(AttachAshPileFunction)
    TSCRIPTFUNC_GENERIC(SetCritStageFunction)
    TSCRIPTFUNC_GENERIC(IsInCritStageFunction)
    TSCRIPTFUNC_GENERIC(RemoveFromAllFactionsFunction)
    TSCRIPTFUNC_GENERIC(GetXPForNextLevelFunction)
    TSCRIPTFUNC_GENERIC(ForceTerminalBackFunction)
    TSCRIPTFUNC_GENERIC(ToggleDepthBiasFunction)
    TSCRIPTFUNC_GENERIC(SetMinimalUseFunction)
    TSCRIPTFUNC_GENERIC(SetPCCanUsePowerArmorFunction)
    TSCRIPTFUNC_GENERIC(ShowQuestStagesFunction)
    TSCRIPTFUNC_GENERIC(ToggleSPURenderBatchFunction)
    TSCRIPTFUNC_GENERIC(ToggleSPUTransformUpdateFunction)
    TSCRIPTFUNC_GENERIC(ForceRSXCrashFunction)
    TSCRIPTFUNC_GENERIC(EvalActorTextures)
    TSCRIPTFUNC_GENERIC(ModifyFaceGen)
    TSCRIPTFUNC_GENERIC(DisableAllMinesFunction)
    TSCRIPTFUNC_GENERIC(DetonatePlacedExplosivesFunction)
    TSCRIPTFUNC_GENERIC(SetEmitterParticleMax)
    TSCRIPTFUNC_GENERIC(SetMPSParticleMax)
    TSCRIPTFUNC_GENERIC(SetTaskThreadSleepFunction)
    TSCRIPTFUNC_GENERIC(SetTaskThreadUpdateSleepFunction)
    TSCRIPTFUNC_GENERIC(SetSecuritronExpression)
    TSCRIPTFUNC_GENERIC(SwapTextureOnRef)
    TSCRIPTFUNC_GET_PVPVRD(UnimplementedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsInCritStageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(HasBeenEatenConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetWeaponHealthPercConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetMapMarkerVisibleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsUsedItemEquipTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetThreatRatioConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsAlignmentConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDestructionStageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPlayerGrabbedRefConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetInZoneConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsWaterObjectConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDistanceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPosConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAngleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetStartingPosConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetStartingAngleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetMenuModeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetSecondsPassedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(HasLoaded3DConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetActorValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPermanentActorValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetBaseActorValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCurrentTimeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetScaleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLOSConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDisabledConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDiseaseConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVampireConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetSandmanConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetClothingValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(SameFactionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(SameRaceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(SameSexConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(SameFactionAsPCConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(SameRaceAsPCConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(SameSexAsPCConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDetectedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDeadConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetItemCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetGoldConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetSleepingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetSittingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFurnitureMarkerIDConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsCurrentFurnitureRefConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsCurrentFurnitureObjConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetTalkedToPCConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetScriptVariableConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetQuestRunningConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetQuestCompletedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetStageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetStageDoneConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFactionRankDifferenceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAlarmedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsPleasantConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsCloudyConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsRainingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsSnowingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetWindSpeedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetWeatherPercentConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsCurrentWeatherConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAttackedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsCreatureConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetShouldAttackConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetInCellConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetInWorldspaceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetInSameCellConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsClassConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsRaceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsCreatureTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsSexConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsPlayableRaceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetInFactionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCIsClassConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCIsRaceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCIsSexConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCInFactionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsIDConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsVoiceTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsChildConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsUsedItemConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsUsedItemTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetUsedItemLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetUsedItemActivateConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsRefConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFactionRankConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetGlobalValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLocalValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDispositionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetRandomPercentConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetArmorRatingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDeadCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAlertConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPlayerControlsDisabledConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetHeadingAngleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsWeaponOutConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsWeaponInListConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsTorchOutConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsShieldOutConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsYieldingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsFacingUpConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsLeftUpConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetKnockedStateConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetWeaponAnimTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsWeaponSkillTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCurrentAIPackageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsWaitingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsIdlePlayingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCrimeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsGuardConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFatiguePercentageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetHealthPercentageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsTalkingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetWalkSpeedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCurrentAIProcedureConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetTrespassWarningLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsTrespassingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsInMyOwnedCellConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsContinuingPackagePCNearConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(CanHaveFlamesConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(HasFlamesConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetOpenStateConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsCurrentPackageConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDayOfWeekConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPCSleepingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPCAMurdererConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDetectionLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLockedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLockLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsLockBrokenConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetEquippedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsSwimmingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAmountStolenSoldConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsInListConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCasinoWinningsLevelConditionalFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPlayerInRegionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCExpelledConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCFactionMurderConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPlayerEnemyofFactionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCFactionAttackConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDestroyedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(HasMagicEffectConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDefaultOpenConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsSpellTargetConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetSpellUsageNumberConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSModeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSTargetHeightConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPersuasionNumberConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetTotalPersuasionNumberConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCannibalConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsClassDefaultConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsMyClassDefaultConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetGhostConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetUnconsciousConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetRestrainedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetOffersServiceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetBarterGoldConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetInvestmentGoldConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsTimePassingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetArmorRatingUpperConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetOwnershipConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCellOwnershipConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsHorseStolenConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPlayerHasLastRiddenHorseConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsSneakingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsRunningConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFriendHitConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsInCombatConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsInInteriorConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsActorUsingATorchConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPCMiscStatConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsActorEvilConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsActorVictimConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIdleDoneOnceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetNoRumorsConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetWhichServiceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsActorRidingHorseConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsInDangerousWaterConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIgnoreFriendlyHitsConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPlayersLastRiddenHorseConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsXboxConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPS3ConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPCConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsEssentialConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsActorConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPlayerMovingIntoNewSpaceConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetTimeDeadConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLastPlayerActionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPlayerActionActiveConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetTalkingActivatorActorConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsActorTalkingThroughActivatorConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetHitLocationConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPC1stPersonConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetHasNoteConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetCauseofDeathConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsLimbGoneConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetKillingBlowLimbConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(HasFriendDispositionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetKillerConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetKillerObjectConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFactionCombatReactionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsMovingConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsTurningConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAnimActionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(ExistsConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetGroupMemberCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetGroupTargetCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPlantedExplosiveConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIsObjectTypeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDialogueEmotionConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetDialogueEmotionValueConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetFactionRelationConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsLastPlayedIdleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(HasPerkConditionFunction)
    TSCRIPTFUNC_GENERIC(DebugMilesPS3Function)
    TSCRIPTFUNC_GENERIC(SetConsoleOutputFileFunction)
    TSCRIPTFUNC_GENERIC(TestRaceSexTerminalFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPlayerTeammateConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetPlayerTeammateCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetActorCrimePlayerEnemyConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetActorFactionPlayerEnemyConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetMinorCrimeCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetMajorCrimeCountConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetAggroRadiusViolatedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetConcussedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetRadiationLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsGreetingPlayerConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetLastHitCriticalConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsCombatTargetConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSRightAreaFreeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSLeftAreaFreeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSBackAreaFreeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSFrontAreaFreeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSRightTargetVisibleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSLeftTargetVisibleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSBackTargetVisibleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetVATSFrontTargetVisibleConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetXPForNextLevelConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetIgnoreCrimeConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsGoreDisabledConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetActorsInHighConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetReputationConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetReputationPctConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetReputationThresholdConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetObjectiveDisplayedConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetObjectiveCompletedConditionFunction)
    TSCRIPTFUNC_GENERIC(ForceFileCacheFunction)
    TSCRIPTFUNC_GENERIC(DumpNiUpdatesFunction)
    TSCRIPTFUNC_GENERIC(SinFunction)
    TSCRIPTFUNC_GENERIC(CosFunction)
    TSCRIPTFUNC_GENERIC(TanFunction)
    TSCRIPTFUNC_GENERIC(SqrtFunction)
    TSCRIPTFUNC_GENERIC(LogFunction)
    TSCRIPTFUNC_GENERIC(AbsFunction)
    TSCRIPTFUNC_GENERIC(AutoDisplayObjectives)
    TSCRIPTFUNC_GENERIC(KillQuestUpdates)
    TSCRIPTFUNC_GENERIC(IsImageSpaceActiveFunction)
    TSCRIPTFUNC_GENERIC(AddFormToFormListFunction)
    TSCRIPTFUNC_GENERIC(AddNPCToLeveledListFunction)
    TSCRIPTFUNC_GENERIC(AddCreatureToLeveledListFunction)
    TSCRIPTFUNC_GENERIC(AddItemToLeveledListFunction)
    TSCRIPTFUNC_GENERIC(RemapWaterTypeFunction)
    TSCRIPTFUNC_GENERIC(IsCodeRedeemedFunction)
    TSCRIPTFUNC_GENERIC(RedeemCodeFunction)
    TSCRIPTFUNC_GENERIC(RevokeCodeFunction)
    TSCRIPTFUNC_GENERIC(EnableWeaponModFunction)
    TSCRIPTFUNC_GENERIC(SetReputationFunction)
    TSCRIPTFUNC_GENERIC(RemoveReputationFunction)
    TSCRIPTFUNC_GENERIC(AddReputationFunction)
    TSCRIPTFUNC_GENERIC(RemoveReputationExactFunction)
    TSCRIPTFUNC_GENERIC(AddReputationExactFunction)
    TSCRIPTFUNC_GENERIC(GetReputationFunction)
    TSCRIPTFUNC_GENERIC(GetReputationPctFunction)
    TSCRIPTFUNC_GENERIC(GetReputationThresholdFunction)
    TSCRIPTFUNC_GENERIC(GetOwnerLastTargetFunction)
    TSCRIPTFUNC_GENERIC(GetForceHitReactionFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetForceHitReactionConditionFunction)
    TSCRIPTFUNC_GENERIC(UnlockChallengeFunction)
    TSCRIPTFUNC_GENERIC(ChallengeLockedFunction)
    TSCRIPTFUNC_GET_PVPVRD(ChallengeLockedConditionFunction)
    TSCRIPTFUNC_GENERIC(GetChallengeCompletedFunction)
    TSCRIPTFUNC_GENERIC(RemoveRecurringFromChallengeFunction)
    TSCRIPTFUNC_GET_PVPVRD(GetChallengeCompletedConditionFunction)
    TSCRIPTFUNC_GENERIC(PlaceAtReticleFunction)
    TSCRIPTFUNC_GENERIC(ObjectUnderReticleFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsPlayerTagSkillConditionFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsHardcoreConditionalFunction)
    TSCRIPTFUNC_GET_PVPVRD(IsAlwaysHardcoreConditionalFunction)
    TSCRIPTFUNC_GENERIC(IsHardcoreFunction)
    TSCRIPTFUNC_GENERIC(SetHardcoreFunction)
    TSCRIPTFUNC_GENERIC(DisableHardcoreTracking)
    TSCRIPTFUNC_GENERIC(IsAlwaysHardcoreFunction)
    TSCRIPTFUNC_GENERIC(ResetXPFunction)
    TSCRIPTFUNC_GENERIC(ToggleDemigodModeFunction)
    TSCRIPTFUNC_GENERIC(ShowRecipeMenu)
    TSCRIPTFUNC_GENERIC(GetCasinoWinningsLevel)
    TSCRIPTFUNC_GENERIC(SetCasinoWinningsLevel)
    TSCRIPTFUNC_GENERIC(GetDLCCountFunction)
    TSCRIPTFUNC_GENERIC(IsDLCInstalledFunction)
    static void AddPendingDisabledReference(TESObjectREFR *, bool);
    static void AddPendingEnabledReference(TESObjectREFR *);
    static bool IsPendingEnabledReference(TESObjectREFR *);
    static bool IsPendingDisabledReference(TESObjectREFR *);
    static bool IsPendingFadeDisabledReference(TESObjectREFR *);
    static void RemoveDelayedScriptActionReference(TESObjectREFR *);
    static void RunDelayedScriptActionsOnReferences();
    static void SetProcessScripts(bool);
    static bool GetProcessScripts();
    static void ClearAllProfilerTimers();
    static void DisplayDebugText(int, int *, int *);
    static void ClearCachedValues();
    static void SetCrimeVictim(TESForm *);
    static void ClearButtonPressed();
    static void ClearOptimizations();
#undef TSCRIPTFUNC_GENERIC
#undef TSCRIPTFUNC_GET_PVPVRD
#pragma endregion
};
